# Testing methods to compare between two models

## Playing around with gene weights dataframes to compare gene weights between models.

In [1]:
import pandas as pd

In [2]:
# read in the csv files of the threshold rna-seq data
stm_threshold_10_90 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/stm_threshold_10_90.csv")
stm_threshold_15_85 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/stm_threshold_15_85.csv")
stm_threshold_25_75 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/stm_threshold_25_75.csv")
mixed_stm_threshold_10_90 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/mixed_stm_threshold_10_90.csv")
mixed_stm_threshold_15_85 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/mixed_stm_threshold_15_85.csv")
mixed_stm_threshold_25_75 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/mixed_stm_threshold_25_75.csv")

In [3]:
stm_threshold_10_90

        genes  threshold_category
0     STM0001                   0
1     STM0002                   0
2     STM0003                   0
3     STM0004                   0
4     STM0005                   0
...       ...                 ...
4666  PSLT106                  -1
4667  PSLT107                  -1
4668  PSLT108                  -1
4669  PSLT110                  -1
4670  PSLT111                  -1

[4671 rows x 2 columns]

In [4]:
df = stm_threshold_10_90.merge(stm_threshold_15_85, on = "genes", how = "left")
df

        genes  threshold_category_x  threshold_category_y
0     STM0001                     0                     0
1     STM0002                     0                     0
2     STM0003                     0                     0
3     STM0004                     0                     0
4     STM0005                     0                     0
...       ...                   ...                   ...
4666  PSLT106                    -1                    -1
4667  PSLT107                    -1                    -1
4668  PSLT108                    -1                    -1
4669  PSLT110                    -1                    -1
4670  PSLT111                    -1                    -1

[4671 rows x 3 columns]

In [5]:
df[df.threshold_category_x != df.threshold_category_y]

        genes  threshold_category_x  threshold_category_y
13    STM0014                     0                    -1
21    STM0022                     0                    -1
24    STM0025                     0                    -1
26    STM0027                     0                    -1
27    STM0028                     0                    -1
...       ...                   ...                   ...
4530  STM4562                     0                     1
4541  STM4573                     0                    -1
4549  STM4581                     0                     1
4554  STM4586                     0                     1
4567  STM4599                     0                     1

[468 rows x 3 columns]

## Playing around with reaction weights

In [6]:
import os
import sys
import argparse
import numpy as np
import pandas as pd

# COBRApy
from cobra.core.configuration import Configuration
from cobra.io import load_model
from cobra.io import save_json_model

#iMATpy
from imatpy.imat import imat
from imatpy.model_creation import generate_model
from imatpy.parse_gpr import gene_to_rxn_weights

In [7]:
os.environ["GRB_LICENSE_FILE"] = "/home/gmvaz/.gurobi.lic"
Configuration().solver = "gurobi"

In [8]:
# load the test S.Tm LT2 GEM in cobrapy
base_model = load_model("STM_v1_0")

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2789960
Academic license 2789960 - for non-commercial use only - registered to gm___@ucdavis.edu

In [9]:
# read in the csv files of the threshold rna-seq data
stm_threshold_10_90 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/stm_threshold_10_90.csv")
stm_threshold_15_85 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/stm_threshold_15_85.csv")
stm_threshold_25_75 = pd.read_csv("/home/gmvaz/2026_GEMs/imat_prep_test/stm_threshold_25_75.csv")

In [10]:
# make each list into a python set
stm_set_10_90 = set(stm_threshold_10_90["genes"].astype(str).str.strip())
stm_set_15_85 = set(stm_threshold_15_85["genes"].astype(str).str.strip())
stm_set_25_75 = set(stm_threshold_25_75["genes"].astype(str).str.strip())

#check
print(len(stm_set_10_90))
print(len(stm_set_15_85))
print(len(stm_set_25_75))

4671
4671
4671

In [11]:
# make a list of all genes in the input model and save it as a set
model_genes = set([g.id for g in base_model.genes])

#check
print(len(model_genes))

1271

In [12]:
# find the genes that exist in the input model and gene weights file
overlap_10_90 = stm_set_10_90.intersection(model_genes)
overlap_15_85 = stm_set_15_85.intersection(model_genes)
overlap_25_75 = stm_set_25_75.intersection(model_genes)

#check
print(len(overlap_10_90))
print(len(overlap_15_85))
print(len(overlap_25_75))

1251
1251
1251

In [13]:
# find genes that exist in the input model but do not appear in the gene weights file
only_model_stm1090 = model_genes.difference(stm_set_10_90)
only_model_stm1585 = model_genes.difference(stm_set_15_85)
only_model_stm2575 = model_genes.difference(stm_set_25_75)

# check
print(len(only_model_stm1090))
print(len(only_model_stm1585))
print(len(only_model_stm2575))

20
20
20

In [14]:
# find genes that exist in the gene weights file but are not in the input model
only_stm_stm1090 = stm_set_10_90.difference(model_genes)
only_stm_stm1585 = stm_set_15_85.difference(model_genes)
only_stm_stm2575 = stm_set_25_75.difference(model_genes)

# check
print(len(only_stm_stm1090))
print(len(only_stm_stm1585))
print(len(only_stm_stm2575))

3420
3420
3420

In [15]:
# subset the gene weights list for each model/sample to only have the genes present in the input model
stm1090_model = stm_threshold_10_90[stm_threshold_10_90["genes"].isin(model_genes)]
stm1585_model = stm_threshold_15_85[stm_threshold_15_85["genes"].isin(model_genes)]
stm2575_model = stm_threshold_25_75[stm_threshold_25_75["genes"].isin(model_genes)]

In [16]:
# there are different amounts of genes in the gene weights lists and in the input model gene list. 
# make a new gene weight list per sample that has all the genes from the input model:
# (1) assign a value of 0 to the 20 genes found in the input model but not in the gene weights list. 
# (2) add the genes that are present in the input model and raw gene weight list. 
# Result: a gene weight list per sample that has only the genes found in the input model and raw gene weights list. 
subset_weights_stm1090 = stm1090_model.set_index("genes")["threshold_category"].reindex(model_genes, fill_value=0)
subset_weights_stm1585 = stm1585_model.set_index("genes")["threshold_category"].reindex(model_genes, fill_value=0)
subset_weights_stm2575 = stm2575_model.set_index("genes")["threshold_category"].reindex(model_genes, fill_value=0)

# check
print(len(subset_weights_stm1090))
print(len(subset_weights_stm1585))
print(len(subset_weights_stm2575))

1271
1271
1271

In [17]:
# convert gene weights to reaction weights using the final gene weights lists with all genes from the input model
rxn_weights_stm1090 = gene_to_rxn_weights(base_model, subset_weights_stm1090)
rxn_weights_stm1585 = gene_to_rxn_weights(base_model, subset_weights_stm1585)
rxn_weights_stm2575 = gene_to_rxn_weights(base_model, subset_weights_stm2575)

# check
print(len(rxn_weights_stm1090))
print(len(rxn_weights_stm1585))
print(len(rxn_weights_stm2575))

2545
2545
2545

In [18]:
stm1090_model = generate_model(model = base_model, rxn_weights = rxn_weights_stm1090, method = "imat_restrictions")
stm1585_model = generate_model(model = base_model, rxn_weights = rxn_weights_stm1585, method = "imat_restrictions")
stm2575_model = generate_model(model = base_model, rxn_weights = rxn_weights_stm2575, method = "imat_restrictions")

Read LP format model from file /tmp/tmpxvtkk12h.lp
Reading time = 0.02 seconds
: 1802 rows, 5090 columns, 19612 nonzeros
Read LP format model from file /tmp/tmpbg6vedeg.lp
Reading time = 0.02 seconds
: 1802 rows, 5090 columns, 19612 nonzeros
Read LP format model from file /tmp/tmpedja8ky9.lp
Reading time = 0.02 seconds
: 1802 rows, 5090 columns, 19612 nonzeros

In [19]:
save_json_model(stm1090_model, "/home/gmvaz/2026_GEMs/stm_model_test/run_051326/stm1090_imat_restrictions.json")
save_json_model(stm1585_model, "/home/gmvaz/2026_GEMs/stm_model_test/run_051326/stm1585_imat_restrictions.json")
save_json_model(stm2575_model, "/home/gmvaz/2026_GEMs/stm_model_test/run_051326/stm2575_imat_restrictions.json")

In [20]:
print(type(rxn_weights_stm1090))
rxn_weights_stm1090

<class 'pandas.core.series.Series'>

3HAD180      0.0
3HAD181      0.0
3HAD40       0.0
3HAD60       0.0
3HAD80       0.0
            ...
12dgr2_ST    0.0
OAL_ST       0.0
OA4L_ST      0.0
OA5L_ST      0.0
OA4VL_ST     0.0
Length: 2545, dtype: float64

In [21]:
df_stm1090 = rxn_weights_stm1090.to_frame()
df_stm1585 = rxn_weights_stm1585.to_frame()
df_stm2575 = rxn_weights_stm2575.to_frame()

In [22]:
df_stm1090

             0
3HAD180    0.0
3HAD181    0.0
3HAD40     0.0
3HAD60     0.0
3HAD80     0.0
...        ...
12dgr2_ST  0.0
OAL_ST     0.0
OA4L_ST    0.0
OA5L_ST    0.0
OA4VL_ST   0.0

[2545 rows x 1 columns]

In [23]:
# merges on index column by default
df = pd.concat([df_stm1090, df_stm1585], axis = 1)
df.columns = ["a", "b"]

In [24]:
df

             a    b
3HAD180    0.0  0.0
3HAD181    0.0  0.0
3HAD40     0.0  0.0
3HAD60     0.0  0.0
3HAD80     0.0  0.0
...        ...  ...
12dgr2_ST  0.0  0.0
OAL_ST     0.0  0.0
OA4L_ST    0.0  0.0
OA5L_ST    0.0  0.0
OA4VL_ST   0.0  0.0

[2545 rows x 2 columns]

In [25]:
stm1090_vs1585_rxnweights = df[df.a != df.b]
stm1090_vs1585_rxnweights

               a    b
ACNAMt2pp    0.0  1.0
ALLTN        0.0  1.0
AOXSr        0.0 -1.0
ARAI         0.0  1.0
ARBt2rpp     0.0  1.0
...          ...  ...
OCDCEAt2pp   0.0  1.0
MUREINLPPTP  0.0  1.0
2HH24DDH1    0.0 -1.0
GALCTND      0.0  1.0
TCBO         0.0 -1.0

[127 rows x 2 columns]

In [26]:
stm1090_vs1585_rxnweights.to_csv('stm1090_vs1585_rxnweights.csv', index=True)

# check reaction bounds

- check reaction bounds in input model
-  does imat_restrictions method change bounds?

In [27]:
for rx in stm1090_model.reactions:
    print(rx.lower_bound, rx.upper_bound, rx.id, rx.name)
    break

0.0 1000.0 3HAD180 3-hydroxyacyl-[acyl-carrier-protein] dehydratase (n-C18:0)

In [28]:
stm1090_model.reactions

[<Reaction 3HAD180 at 0x132eb309eb50>,
 <Reaction 3HAD181 at 0x132eb2d13d10>,
 <Reaction 3HAD40 at 0x132eb309d190>,
 <Reaction 3HAD60 at 0x132eb3094e90>,
 <Reaction 3HAD80 at 0x132eb3093490>,
 <Reaction 3KGK at 0x132eb2cf3210>,
 <Reaction 3NTD2pp at 0x132eb3093a10>,
 <Reaction 3NTD4pp at 0x132eb3092d10>,
 <Reaction 3NTD7pp at 0x132eb3092050>,
 <Reaction 3NTD9pp at 0x132eb3093bd0>,
 <Reaction 3OAR100 at 0x132eb308b950>,
 <Reaction 3OAR120 at 0x132eb308bf90>,
 <Reaction 3OAR121 at 0x132eb3089a10>,
 <Reaction 3OAR140 at 0x132eb3089f10>,
 <Reaction 3OAR141 at 0x132eb3089910>,
 <Reaction 3OAR160 at 0x132eb30892d0>,
 <Reaction 3OAR161 at 0x132eb3089090>,
 <Reaction 23CAMPtex at 0x132eb30904d0>,
 <Reaction 23CCMPtex at 0x132eb3080b50>,
 <Reaction 23CGMPtex at 0x132eb3080310>,
 <Reaction 12DGR120tipp at 0x132eb3077510>,
 <Reaction 12DGR140tipp at 0x132eb3077550>,
 <Reaction 12DGR141tipp at 0x132eb3076b90>,
 <Reaction 12DGR160tipp at 0x132eb3076d90>,
 <Reaction 23CUMPtex at 0x132eb3077150>,
 <Reaction 3OAR180 at 0x132eb292eed0>,
 <Reaction 23DAPPAt2pp at 0x132eb292ee10>,
 <Reaction 23DAPPAtex at 0x132eb30752d0>,
 <Reaction 12DGR161tipp at 0x132eb2d1ced0>,
 <Reaction 12DGR180tipp at 0x132eb3074f90>,
 <Reaction 12DGR181tipp at 0x132eb3075050>,
 <Reaction 12PPDRtex at 0x132eb30689d0>,
 <Reaction 12PPDRtpp at 0x132eb3093250>,
 <Reaction 12PPDStex at 0x132eb3093210>,
 <Reaction 12PPDStpp at 0x132eb3088ad0>,
 <Reaction 23PDE2pp at 0x132eb3069f90>,
 <Reaction 23PDE4pp at 0x132eb3069a50>,
 <Reaction 23PDE7pp at 0x132eb3068e90>,
 <Reaction 23PDE9pp at 0x132eb3080a90>,
 <Reaction 26DAHtex at 0x132eb30685d0>,
 <Reaction 2AGPA120tipp at 0x132eb2d1d810>,
 <Reaction 2AGPA140tipp at 0x132ec7d24710>,
 <Reaction 2AGPA141tipp at 0x132eb305f6d0>,
 <Reaction 2AGPA160tipp at 0x132eb292dc90>,
 <Reaction 2AGPA161tipp at 0x132eb305f550>,
 <Reaction 2AGPA180tipp at 0x132eb305e950>,
 <Reaction 2AGPA181tipp at 0x132eb305db50>,
 <Reaction 14GLUCANabcpp at 0x132eb305ded0>,
 <Reaction 14GLUCANtexi at 0x132eb3074d50>,
 <Reaction 2AGPE120tipp at 0x132eb305da90>,
 <Reaction 3OAR181 at 0x132eb305d2d0>,
 <Reaction 2AGPE140tipp at 0x132eb3053810>,
 <Reaction 2AGPE141tipp at 0x132eb3051150>,
 <Reaction 3OAR40 at 0x132eb3052dd0>,
 <Reaction 2AGPE160tipp at 0x132eb29e0150>,
 <Reaction 3OAR60 at 0x132eb3053d90>,
 <Reaction 2AGPE161tipp at 0x132eb3051c50>,
 <Reaction 2AGPE180tipp at 0x132eb30532d0>,
 <Reaction 2AGPE181tipp at 0x132eb2cf3490>,
 <Reaction 2AGPEAT120 at 0x132eb3051c10>,
 <Reaction ABUTtex at 0x132eb3050850>,
 <Reaction ACACtex at 0x132eb29d82d0>,
 <Reaction ACALD at 0x132ec7cdbd90>,
 <Reaction ACALDtex at 0x132eb2d0acd0>,
 <Reaction ACALDtpp at 0x132eb3053490>,
 <Reaction 2AGPEAT140 at 0x132eb308bf10>,
 <Reaction 3OAR80 at 0x132eb304b1d0>,
 <Reaction 2AGPEAT141 at 0x132eb304ae10>,
 <Reaction 2AGPEAT160 at 0x132eb304ad50>,
 <Reaction ACBIPGT at 0x132eb304a610>,
 <Reaction ACCOAC at 0x132eb3049fd0>,
 <Reaction 2AGPEAT161 at 0x132eb3068a90>,
 <Reaction ACCOAL at 0x132eb3080d90>,
 <Reaction 3OAS100 at 0x132eb3048fd0>,
 <Reaction ACGAL1PPpp at 0x132eb303c610>,
 <Reaction 2AGPEAT180 at 0x132eb303ce90>,
 <Reaction 2AGPEAT181 at 0x132eb3077190>,
 <Reaction 2AGPG120tipp at 0x132eb2d08750>,
 <Reaction ACGAL1Ptex at 0x132eb303eb90>,
 <Reaction 3OAS120 at 0x132eb3077f10>,
 <Reaction ACGALtex at 0x132eb2d1d290>,
 <Reaction ACGAM1PPpp at 0x132eb303e990>,
 <Reaction 2AGPG140tipp at 0x132eb303c990>,
 <Reaction 2AGPG141tipp at 0x132eb309d310>,
 <Reaction 2AGPG160tipp at 0x132eb305c710>,
 <Reaction ACGAM1Ptex at 0x132eb303c650>,
 <Reaction ACGAMK at 0x132eb304bad0>,
 <Reaction ACGAMT at 0x132eb3080d50>,
 <Reaction 2AGPG161tipp at 0x132eb3048a90>,
 <Reaction 2AGPG180tipp at 0x132eb3033c10>,
 <Reaction 2AGPG181tipp at 0x132eb308b890>,
 <Reaction ACGAptspp at 0x132eb3033510>,
 <Reaction ACGAtex at 0x132eb3091910>,
 <Reaction 2AGPGAT120 at 0x132eb3091710>,
 <Reaction ACGK at 0x132eb3030690>,
 <Reaction 2AGPGAT140 at 0x132eb3030610>,
 <Reaction 3OAS121 at 0x132eb304b4d0>,
 <Reaction 2AGPGAT141 at 0x132eb3026c90>,
 <Reaction 2AGPGAT160 at 0x132eb3026110>,
 <Reaction ACGS at 0x132eb3025fd0>,
 <Reaction ACHBS at 0x132eb30242d0>,
 <Reaction 3OAS140 at 0x132eb3077650>,
 <Reaction ACKr at 0x132eb30971d0>,
 <Reaction ACLS at 0x132eb305e810>,
 <Reaction 2AGPGAT161 at 0x132eb309d5d0>,
 <Reaction 2AGPGAT180 at 0x132eb3025510>,
 <Reaction 2AGPGAT181 at 0x132eb305f050>,
 <Reaction ACM6PH at 0x132eb30243d0>,
 <Reaction 3OAS141 at 0x132eb3023210>,
 <Reaction ACMAMUT at 0x132eb3021390>,
 <Reaction 3OAS160 at 0x132eb3023e50>,
 <Reaction ACMANAptspp at 0x132eb3030e90>,
 <Reaction 3OAS161 at 0x132eb304b490>,
 <Reaction ACMANAtex at 0x132eb3033650>,
 <Reaction ACMUMtex at 0x132eb3021dd0>,
 <Reaction 2DGLCNRx at 0x132eb29e1a50>,
 <Reaction 2DGLCNRy at 0x132eb3f02190>,
 <Reaction 2DGULRx at 0x132eb3020d90>,
 <Reaction 2DGULRy at 0x132eb3020a10>,
 <Reaction ACNAMt2pp at 0x132eb3020390>,
 <Reaction ACNAMtex at 0x132eb3019210>,
 <Reaction ACNML at 0x132eb304bf10>,
 <Reaction ACOAD1f at 0x132eb301bc50>,
 <Reaction ACOAD2f at 0x132eb3049e90>,
 <Reaction 2MAHMP at 0x132eb301b010>,
 <Reaction 3OAS180 at 0x132eb3031490>,
 <Reaction 34dhpactex at 0x132eb308a510>,
 <Reaction 3AMPtex at 0x132eb29e1c50>,
 <Reaction ACOAD3f at 0x132eb2d11a90>,
 <Reaction ACOAD4f at 0x132eb3021c90>,
 <Reaction ACOAD5f at 0x132eb3019410>,
 <Reaction 3CMPtex at 0x132eb3018110>,
 <Reaction 3OAS181 at 0x132eb3008dd0>,
 <Reaction 3GMPtex at 0x132eb300bd90>,
 <Reaction 3HAD100 at 0x132ec7cdbc90>,
 <Reaction 3HAD120 at 0x132eb3093610>,
 <Reaction ACOAD6f at 0x132eb30231d0>,
 <Reaction ACOAD7f at 0x132eb300a450>,
 <Reaction ACOAD8f at 0x132eb300b0d0>,
 <Reaction ACOATA at 0x132eb300a6d0>,
 <Reaction 3HAD121 at 0x132eb3080c90>,
 <Reaction ACODA at 0x132eb30081d0>,
 <Reaction 3OAS60 at 0x132ec7c1e190>,
 <Reaction 3HAD140 at 0x132eb30068d0>,
 <Reaction 3OAS80 at 0x132eb3077590>,
 <Reaction 3HAD141 at 0x132eb303f890>,
 <Reaction 3PEPTabcpp at 0x132eb3007990>,
 <Reaction 3HAD160 at 0x132eb303c9d0>,
 <Reaction 3HAD161 at 0x132eb3076290>,
 <Reaction ACOLIPAtex at 0x132eb292cf90>,
 <Reaction ACONIs at 0x132eb30050d0>,
 <Reaction ACONTa at 0x132eb3004fd0>,
 <Reaction ACONTb at 0x132eb303c190>,
 <Reaction ADK1 at 0x132eb3004690>,
 <Reaction ADK3 at 0x132eb2ff6090>,
 <Reaction ACOTA at 0x132eb2ff4110>,
 <Reaction 3PEPTtex at 0x132eb305d650>,
 <Reaction ACPS1 at 0x132eb305e650>,
 <Reaction ACS at 0x132eb303fb10>,
 <Reaction ACSERtex at 0x132eb3027290>,
 <Reaction ADK4 at 0x132eb2d1f190>,
 <Reaction ADMDC at 0x132eb2ff6f90>,
 <Reaction ADNCYC at 0x132eb2ff6390>,
 <Reaction 3UMPtex at 0x132eb2ff6110>,
 <Reaction ADNK1 at 0x132eb303c850>,
 <Reaction ADNUC at 0x132eb305c790>,
 <Reaction ADNt2pp_copy1 at 0x132eb3004190>,
 <Reaction ACSERtpp at 0x132eb301a510>,
 <Reaction ACt2rpp at 0x132eb3052e50>,
 <Reaction ACt4pp at 0x132eb2feadd0>,
 <Reaction ADNt2pp_copy2 at 0x132eb2feba90>,
 <Reaction 4HOXPACDtex at 0x132eb3092b90>,
 <Reaction ADNtex at 0x132eb301af50>,
 <Reaction ADOCBLabcpp at 0x132eb2feabd0>,
 <Reaction ACtex at 0x132eb2fe9f50>,
 <Reaction ADA at 0x132eb3021e10>,
 <Reaction ADCL at 0x132eb2fe9e90>,
 <Reaction ADOCBLtonex at 0x132eb2fe99d0>,
 <Reaction ADPRDP at 0x132eb3030890>,
 <Reaction ADCS at 0x132eb2fe8950>,
 <Reaction ADEt2rpp at 0x132eb2fe85d0>,
 <Reaction ADEtex at 0x132eb2fe2d50>,
 <Reaction ADPT at 0x132eb2fe3e50>,
 <Reaction ADSK at 0x132eb2fe3dd0>,
 <Reaction ADSL1r at 0x132eb2fe3a50>,
 <Reaction 4PCP at 0x132eb3053c10>,
 <Reaction ADSL2r at 0x132eb2fe3150>,
 <Reaction ADSS at 0x132eb2fe2cd0>,
 <Reaction AGDC at 0x132eb2fe2810>,
 <Reaction ALDD3y at 0x132eb2fe3190>,
 <Reaction ALLTAMH at 0x132ed5011c50>,
 <Reaction AGM3PA at 0x132eb29e1e90>,
 <Reaction 4PCPpp at 0x132eb2fe1bd0>,
 <Reaction AGM3PApp at 0x132eb2fe2110>,
 <Reaction AGM3PH at 0x132eb3020950>,
 <Reaction ALLTN at 0x132eb2fe1450>,
 <Reaction ALLTNt2rpp at 0x132eb2fe1090>,
 <Reaction AGM3Pt2pp at 0x132eb2fe0ad0>,
 <Reaction ALLTNtex at 0x132eb2fe05d0>,
 <Reaction AGM4PA at 0x132eb2fda110>,
 <Reaction 4PEPTabcpp at 0x132eb2fdab90>,
 <Reaction AGM4PApp at 0x132eb29d8d10>,
 <Reaction ALLtex at 0x132eb300b610>,
 <Reaction 4PEPTtex at 0x132eb30930d0>,
 <Reaction ALR2 at 0x132eb3091990>,
 <Reaction ALR4x at 0x132eb2fda210>,
 <Reaction AGM4PCP at 0x132eb2fda350>,
 <Reaction AGM4PCPpp at 0x132eb2fda690>,
 <Reaction AM3PA at 0x132eb2fda150>,
 <Reaction AM4PA at 0x132eb2fd9510>,
 <Reaction 5DGLCNR at 0x132eb2fd9550>,
 <Reaction AM4PCP at 0x132eb2fd9690>,
 <Reaction AMALT1 at 0x132eb29d8690>,
 <Reaction AMALT2 at 0x132eb2fd8590>,
 <Reaction AMALT3 at 0x132eb2fd8450>,
 <Reaction AMALT4 at 0x132eb31c0690>,
 <Reaction AGM4PH at 0x132eb31c3190>,
 <Reaction AGM4Pt2pp at 0x132eb31c31d0>,
 <Reaction AGMH at 0x132eb31c3a10>,
 <Reaction AGMHE at 0x132eb2fe3c10>,
 <Reaction AGMT at 0x132eb31c36d0>,
 <Reaction AGMt2pp at 0x132eb31c3d10>,
 <Reaction AMANAPEr at 0x132eb31c3bd0>,
 <Reaction AMANK at 0x132eb3091a90>,
 <Reaction AMAOTr at 0x132eb31c2490>,
 <Reaction AGMtex at 0x132eb31c2f50>,
 <Reaction 5DGLCNt2rpp at 0x132eb3031390>,
 <Reaction AGPAT120 at 0x132eb31c2390>,
 <Reaction AGPAT140 at 0x132eb2d09ad0>,
 <Reaction AMMQLT8 at 0x132eb3080ed0>,
 <Reaction AMPMS2 at 0x132eb31c1350>,
 <Reaction 5DGLCNtex at 0x132eb30191d0>,
 <Reaction AMPN at 0x132eb31c1710>,
 <Reaction AMPTASECG at 0x132eb31c18d0>,
 <Reaction AMPTASEPG at 0x132eb31c0110>,
 <Reaction AGPAT141 at 0x132eb303d7d0>,
 <Reaction AGPAT160 at 0x132eb31bdf10>,
 <Reaction AGPAT161 at 0x132eb31bfd90>,
 <Reaction AMPtex at 0x132eb303f8d0>,
 <Reaction 5DOAN at 0x132eb31bff10>,
 <Reaction ANHGMtex at 0x132eb31bfed0>,
 <Reaction ANHMK at 0x132eb303ecd0>,
 <Reaction AGPAT180 at 0x132eb31beb10>,
 <Reaction AGPAT181 at 0x132eb31bdb90>,
 <Reaction AGPR at 0x132eb31bd9d0>,
 <Reaction AHCYSNS at 0x132eb305ef50>,
 <Reaction ANPRT at 0x132eb31bd550>,
 <Reaction ANS at 0x132eb2fdb590>,
 <Reaction AOBUTDs at 0x132eb31bd290>,
 <Reaction AOXSr at 0x132eb31bc1d0>,
 <Reaction AP4AH at 0x132eb31c3c10>,
 <Reaction AICART at 0x132eb31b3710>,
 <Reaction AIRC2 at 0x132eb31b3650>,
 <Reaction AP5AH at 0x132eb31b3cd0>,
 <Reaction A5PISO at 0x132eb31b3a50>,
 <Reaction APRAUR at 0x132eb31b3050>,
 <Reaction AIRC3 at 0x132eb31b2f50>,
 <Reaction AKGDH at 0x132eb31b2a10>,
 <Reaction ARAI at 0x132eb31b1c10>,
 <Reaction AACPS1 at 0x132eb31b1fd0>,
 <Reaction ARBTNR1 at 0x132eb2d08890>,
 <Reaction ARBTNR2 at 0x132eb31b2010>,
 <Reaction AKGt2rpp at 0x132eb31b1bd0>,
 <Reaction AKGtex at 0x132eb31b1c50>,
 <Reaction ARBTNR3 at 0x132eb31b0f90>,
 <Reaction ALAALAabcpp at 0x132eb31b0dd0>,
 <Reaction AACPS2 at 0x132eb31b1110>,
 <Reaction ALAALAr at 0x132eb31a2b90>,
 <Reaction ALAALAtex at 0x132eb3049190>,
 <Reaction ARBTNabcpp at 0x132eb31a3f90>,
 <Reaction ARBTNexs at 0x132eb3052fd0>,
 <Reaction ARBTNtex at 0x132eb31a2610>,
 <Reaction ALAGLUE at 0x132eb31a3750>,
 <Reaction ALAR at 0x132eb31a2f90>,
 <Reaction ALATA_D2 at 0x132eb31a3010>,
 <Reaction AACPS3 at 0x132eb3022190>,
 <Reaction ALATA_L at 0x132eb31c11d0>,
 <Reaction ALATA_L2 at 0x132eb31a16d0>,
 <Reaction ALATRS at 0x132eb2fe8790>,
 <Reaction ALAabcpp at 0x132eb31a0c10>,
 <Reaction ARBTNtonex at 0x132eb31a06d0>,
 <Reaction ARBTNtpp at 0x132eb20aca90>,
 <Reaction ARBt2rpp at 0x132eb20ad550>,
 <Reaction ARBt3ipp at 0x132eb31be890>,
 <Reaction ARBtex at 0x132eb20afb90>,
 <Reaction ARGAGMt7pp at 0x132eb305fd90>,
 <Reaction ALAt2pp at 0x132eb20afbd0>,
 <Reaction ALAt4pp at 0x132eb20af410>,
 <Reaction ARGDC at 0x132eb20ae350>,
 <Reaction AACPS4 at 0x132eb20aebd0>,
 <Reaction ARGDCpp at 0x132eb20ad7d0>,
 <Reaction ARGORNt7pp at 0x132eb20ad310>,
 <Reaction ALAtex at 0x132eb20ad810>,
 <Reaction ALDD2y at 0x132eb20ace90>,
 <Reaction ARGSL at 0x132eb20ac3d0>,
 <Reaction AACPS5 at 0x132eb20ac650>,
 <Reaction ARGSS at 0x132eb3094ad0>,
 <Reaction ARGTRS at 0x132eb3094cd0>,
 <Reaction ASNNpp at 0x132eb319e5d0>,
 <Reaction AACPS6 at 0x132eb319f8d0>,
 <Reaction ASNS1 at 0x132eb319f850>,
 <Reaction ARGabcpp at 0x132eb319f3d0>,
 <Reaction ARGt3pp at 0x132eb31a0790>,
 <Reaction ASNS2 at 0x132eb319e650>,
 <Reaction AACPS7 at 0x132eb319e490>,
 <Reaction ARGtex at 0x132eb319d350>,
 <Reaction ASAD at 0x132eb3024810>,
 <Reaction AACPS8 at 0x132eb319c7d0>,
 <Reaction ASCBPL at 0x132eb318ee50>,
 <Reaction ASCBptspp at 0x132eb3076210>,
 <Reaction ASCBtex at 0x132eb318fb50>,
 <Reaction AACPS9 at 0x132eb303ee90>,
 <Reaction ASNN at 0x132eb2ff79d0>,
 <Reaction AACTOOR at 0x132eb303ec90>,
 <Reaction AAMYL at 0x132eb318e950>,
 <Reaction ASNTRS_1 at 0x132eb318e4d0>,
 <Reaction AAMYLpp at 0x132eb318e190>,
 <Reaction ASNabcpp at 0x132eb318c9d0>,
 <Reaction ABTA at 0x132eb318d510>,
 <Reaction ASNt2rpp at 0x132eb318d5d0>,
 <Reaction ABUTD at 0x132eb318c890>,
 <Reaction ASNtex at 0x132eb318c910>,
 <Reaction ASO3tex at 0x132eb20afd10>,
 <Reaction ABUTt2pp at 0x132eb3007490>,
 <Reaction ASP1DC at 0x132eb20af590>,
 <Reaction CRNDCAL2 at 0x132eb317f850>,
 <Reaction ASPCT at 0x132eb317f990>,
 <Reaction ASPK at 0x132eb319e7d0>,
 <Reaction ASPO3 at 0x132eb3076b10>,
 <Reaction ASPO4 at 0x132eb317e850>,
 <Reaction ASPO5 at 0x132eb318ee90>,
 <Reaction ASPO6 at 0x132eb317ce90>,
 <Reaction CDPMEK at 0x132eb317da10>,
 <Reaction CFAS160E at 0x132eb317d2d0>,
 <Reaction CFAS160G at 0x132eb317ce50>,
 <Reaction CFAS180E at 0x132eb3094a90>,
 <Reaction CRNDabcpp at 0x132eb3074ed0>,
 <Reaction CFAS180G at 0x132eb301bf90>,
 <Reaction CGLYabcpp at 0x132eb3179510>,
 <Reaction ASPT at 0x132eb3033950>,
 <Reaction ASPTA at 0x132eb317bd50>,
 <Reaction CGLYtex at 0x132eb317a210>,
 <Reaction CHLabcpp at 0x132eb2fe95d0>,
 <Reaction CHLtex at 0x132eb31798d0>,
 <Reaction ASPTRS at 0x132eb31c1d10>,
 <Reaction ASPabcpp at 0x132eb3179ad0>,
 <Reaction ASPt2_2pp at 0x132eb30488d0>,
 <Reaction ASPt2pp at 0x132eb3178690>,
 <Reaction CHORS at 0x132eb31789d0>,
 <Reaction CHRPL at 0x132eb31700d0>,
 <Reaction ASPtex at 0x132eb3171b90>,
 <Reaction AST at 0x132eb308b810>,
 <Reaction CITL at 0x132eb3173c50>,
 <Reaction CRNDt2rpp at 0x132eb3173ad0>,
 <Reaction CITt7pp at 0x132eb31724d0>,
 <Reaction CITtex at 0x132eb3172710>,
 <Reaction ATHRDHr at 0x132eb2fd8350>,
 <Reaction ATPHs at 0x132eb3170ed0>,
 <Reaction ATPM at 0x132eb3170650>,
 <Reaction CRNabcpp at 0x132eb3170150>,
 <Reaction ATPPRT at 0x132eb3164ed0>,
 <Reaction CRNt2rpp at 0x132eb318d2d0>,
 <Reaction ATPS4rpp at 0x132eb3167990>,
 <Reaction ICITtex at 0x132eb20add10>,
 <Reaction CRNt7pp at 0x132eb31bed90>,
 <Reaction ACONCtex at 0x132eb317dd50>,
 <Reaction BALAt2pp at 0x132eb3074c50>,
 <Reaction BALAtex at 0x132eb3164990>,
 <Reaction CRNt8pp at 0x132eb31648d0>,
 <Reaction BPNT at 0x132eb31bdc90>,
 <Reaction BSORx at 0x132eb315cc50>,
 <Reaction BSORy at 0x132eb315e810>,
 <Reaction BTS4 at 0x132eb315c310>,
 <Reaction BUTSO3tex at 0x132eb315ee10>,
 <Reaction CLIPAtex at 0x132eb20afe90>,
 <Reaction CLPNH120pp at 0x132eb315c5d0>,
 <Reaction CLPNH140pp at 0x132eb315fcd0>,
 <Reaction CLPNH141pp at 0x132eb315ea50>,
 <Reaction CLPNH160pp at 0x132eb315e950>,
 <Reaction CLPNH161pp at 0x132eb315f010>,
 <Reaction CLPNH180pp at 0x132eb315e710>,
 <Reaction BUTtex at 0x132eb315ed90>,
 <Reaction CLPNH181pp at 0x132eb2d2d010>,
 <Reaction CRNtex at 0x132eb315da10>,
 <Reaction CLPNS120pp at 0x132eb20afad0>,
 <Reaction CA2t3pp at 0x132eb31bc490>,
 <Reaction CS at 0x132eb3157350>,
 <Reaction CA2tex at 0x132eb3157c10>,
 <Reaction CADVtpp at 0x132eb3006450>,
 <Reaction CLPNS140pp at 0x132eb3157190>,
 <Reaction CLPNS141pp at 0x132eb30769d0>,
 <Reaction CAt6pp at 0x132ec7c1e290>,
 <Reaction CLPNS160pp at 0x132eb3156310>,
 <Reaction CSNtex at 0x132eb318e210>,
 <Reaction CLPNS161pp at 0x132eb292ebd0>,
 <Reaction CLPNS180pp at 0x132eb3154710>,
 <Reaction CBIAT at 0x132eb319cad0>,
 <Reaction CBItonex at 0x132eb3154950>,
 <Reaction CBIuabcpp at 0x132eb3157550>,
 <Reaction CBL1abcpp at 0x132eb31474d0>,
 <Reaction CLPNS181pp at 0x132eb3146b50>,
 <Reaction CTBTCAL2 at 0x132eb31462d0>,
 <Reaction CLt3_2pp at 0x132eb3145f10>,
 <Reaction CLtex at 0x132eb292e0d0>,
 <Reaction CMPN at 0x132eb3074b50>,
 <Reaction CMPtex at 0x132eb3004890>,
 <Reaction CBL1tonex at 0x132eb30946d0>,
 <Reaction CBPS at 0x132eb313ed10>,
 <Reaction CD2abcpp at 0x132eb313cd10>,
 <Reaction CD2t3pp at 0x132eb313ff50>,
 <Reaction CD2tex at 0x132eb30276d0>,
 <Reaction CD2tpp at 0x132eb2d1f610>,
 <Reaction CDAPPA120 at 0x132eb313f1d0>,
 <Reaction CO2tex at 0x132eb313e9d0>,
 <Reaction CO2tpp at 0x132eb2d11410>,
 <Reaction CDAPPA140 at 0x132eb313d590>,
 <Reaction CTBTabcpp at 0x132eb313d650>,
 <Reaction CDAPPA141 at 0x132eb30255d0>,
 <Reaction CDAPPA160 at 0x132eb313d410>,
 <Reaction COBALT2abcpp at 0x132eb313cb10>,
 <Reaction COBALT2t3pp at 0x132eb312fdd0>,
 <Reaction COBALT2tex at 0x132eb312f790>,
 <Reaction CTBTt2rpp at 0x132eb20ae890>,
 <Reaction COBALT2tpp_copy1 at 0x132eb312e1d0>,
 <Reaction COLIPAabcpp at 0x132eb313f450>,
 <Reaction COLIPAtex at 0x132eb312e5d0>,
 <Reaction CDAPPA161 at 0x132eb312f750>,
 <Reaction CDAPPA180 at 0x132eb312f250>,
 <Reaction CDAPPA181 at 0x132eb312e850>,
 <Reaction CPGNR1 at 0x132eb312e550>,
 <Reaction CTPS2 at 0x132eb312d790>,
 <Reaction CPGNR2 at 0x132eb312db90>,
 <Reaction CPGNR3 at 0x132eb312d310>,
 <Reaction CU1Opp at 0x132eb312d0d0>,
 <Reaction CPGNUtex at 0x132eb312c310>,
 <Reaction CPGNUtpp at 0x132eb312c550>,
 <Reaction CPGNabcpp at 0x132eb3127150>,
 <Reaction CPGNexs at 0x132eb3124e90>,
 <Reaction DAMPtex at 0x132eb2d1da90>,
 <Reaction DAPDC at 0x132eb3097390>,
 <Reaction DAPE at 0x132eb3127350>,
 <Reaction DAPabcpp at 0x132eb31270d0>,
 <Reaction DAPtex at 0x132eb31460d0>,
 <Reaction CPGNtonex at 0x132eb3025890>,
 <Reaction CU1abcpp at 0x132eb3124590>,
 <Reaction CPPPGO at 0x132eb3124450>,
 <Reaction CPPPGO2 at 0x132eb3124650>,
 <Reaction DASYN120 at 0x132eb31249d0>,
 <Reaction DASYN140 at 0x132eb311de50>,
 <Reaction CRNBTCT at 0x132eb3097310>,
 <Reaction AU1abcpp at 0x132eb311e990>,
 <Reaction CRNCAL2 at 0x132eb311f690>,
 <Reaction CRNCAR at 0x132eb311eb50>,
 <Reaction CRNCBCT at 0x132eb311f290>,
 <Reaction DASYN141 at 0x132eb311e390>,
 <Reaction DASYN160 at 0x132eb311db90>,
 <Reaction DASYN161 at 0x132eb311db10>,
 <Reaction DASYN180 at 0x132eb311d810>,
 <Reaction CRNCDH at 0x132eb3004c90>,
 <Reaction CU2abcpp at 0x132eb311cb90>,
 <Reaction DASYN181 at 0x132eb31c0f90>,
 <Reaction DATPHs at 0x132eb3113690>,
 <Reaction CU2tex at 0x132eb3110690>,
 <Reaction DB4PS at 0x132eb3092c90>,
 <Reaction DBTS at 0x132eb3113390>,
 <Reaction DMQMT at 0x132eb301a8d0>,
 <Reaction CU2tpp at 0x132eb3112a10>,
 <Reaction DMSOtex at 0x132eb3111d90>,
 <Reaction DMStex at 0x132eb2d11c10>,
 <Reaction DM_4hba_c at 0x132eb31b0890>,
 <Reaction DCAtex at 0x132eb3110810>,
 <Reaction DCMPtex at 0x132eb2d08ed0>,
 <Reaction DCTPD at 0x132eb301bf10>,
 <Reaction DCYTD at 0x132eb3033890>,
 <Reaction DCYTt2pp at 0x132eb310b490>,
 <Reaction CUtex at 0x132eb2feae50>,
 <Reaction DCYTtex at 0x132eb306b2d0>,
 <Reaction DDCAtexi at 0x132eb310ac10>,
 <Reaction DDGALK at 0x132eb310a710>,
 <Reaction DM_5drib_c at 0x132eb310a610>,
 <Reaction DM_hmfurn_c at 0x132eb310a650>,
 <Reaction DM_oxam_c at 0x132eb310a450>,
 <Reaction DNMPPA at 0x132eb3109c10>,
 <Reaction DNTPPA at 0x132eb3108e10>,
 <Reaction DDGLCNtex at 0x132eb30918d0>,
 <Reaction CYANST at 0x132eb3108810>,
 <Reaction DDGLK at 0x132eb3108650>,
 <Reaction DDPA at 0x132eb30fd050>,
 <Reaction DGK1 at 0x132eb3025590>,
 <Reaction DOGULNR at 0x132eb30fc510>,
 <Reaction DOPAtex at 0x132eb30fcd50>,
 <Reaction DPCOAK at 0x132eb20afd90>,
 <Reaction DRPA at 0x132eb30ffe90>,
 <Reaction DGMPtex at 0x132eb30ffc50>,
 <Reaction DGSNt2pp at 0x132eb313d9d0>,
 <Reaction CYANSTpp at 0x132eb3165cd0>,
 <Reaction DGSNtex at 0x132eb30fe3d0>,
 <Reaction DSBAO1 at 0x132eb30fc210>,
 <Reaction DSBAO2 at 0x132eb30f8490>,
 <Reaction DSBCGT at 0x132eb2d01390>,
 <Reaction DSBDR at 0x132eb30f8dd0>,
 <Reaction DSBGGT at 0x132eb310bf10>,
 <Reaction DHAD1 at 0x132eb30fbfd0>,
 <Reaction DHAD2 at 0x132eb30fbc50>,
 <Reaction DHAtex at 0x132eb30fac50>,
 <Reaction DHAtpp at 0x132eb301a290>,
 <Reaction DHBD at 0x132eb30fa510>,
 <Reaction DSERDHr at 0x132eb30fa410>,

In [29]:
# create two dictionaries in python. dictionaries store key-value pairs
lower_bounds = {}
upper_bounds = {}

for rx in stm1090_model.reactions:
    lower_bounds[rx.id] = rx.lower_bound
    upper_bounds[rx.id] = rx.upper_bound

In [30]:
lower_bounds

{'3HAD180': 0.0,
 '3HAD181': 0.0,
 '3HAD40': 0.0,
 '3HAD60': 0.0,
 '3HAD80': 0.0,
 '3KGK': 0.0,
 '3NTD2pp': 0.0,
 '3NTD4pp': 0.0,
 '3NTD7pp': 0.0,
 '3NTD9pp': 0.0,
 '3OAR100': -1000.0,
 '3OAR120': -1000.0,
 '3OAR121': 0.0,
 '3OAR140': -1000.0,
 '3OAR141': 0.0,
 '3OAR160': -1000.0,
 '3OAR161': 0.0,
 '23CAMPtex': -1000.0,
 '23CCMPtex': -1000.0,
 '23CGMPtex': -1000.0,
 '12DGR120tipp': 0.0,
 '12DGR140tipp': 0.0,
 '12DGR141tipp': 0.0,
 '12DGR160tipp': 0.0,
 '23CUMPtex': -1000.0,
 '3OAR180': -1000.0,
 '23DAPPAt2pp': 0.0,
 '23DAPPAtex': -1000.0,
 '12DGR161tipp': 0.0,
 '12DGR180tipp': 0.0,
 '12DGR181tipp': 0.0,
 '12PPDRtex': -1000.0,
 '12PPDRtpp': -1000.0,
 '12PPDStex': -1000.0,
 '12PPDStpp': -1000.0,
 '23PDE2pp': 0.0,
 '23PDE4pp': 0.0,
 '23PDE7pp': 0.0,
 '23PDE9pp': 0.0,
 '26DAHtex': -1000.0,
 '2AGPA120tipp': 0.0,
 '2AGPA140tipp': 0.0,
 '2AGPA141tipp': 0.0,
 '2AGPA160tipp': 0.0,
 '2AGPA161tipp': 0.0,
 '2AGPA180tipp': 0.0,
 '2AGPA181tipp': 0.0,
 '14GLUCANabcpp': 0.0,
 '14GLUCANtexi': 0.0,
 '2AGPE120tipp': 0.0,
 '3OAR181': 0.0,
 '2AGPE140tipp': 0.0,
 '2AGPE141tipp': 0.0,
 '3OAR40': -1000.0,
 '2AGPE160tipp': 0.0,
 '3OAR60': -1000.0,
 '2AGPE161tipp': 0.0,
 '2AGPE180tipp': 0.0,
 '2AGPE181tipp': 0.0,
 '2AGPEAT120': 0.0,
 'ABUTtex': -1000.0,
 'ACACtex': -1000.0,
 'ACALD': -1000.0,
 'ACALDtex': -1000.0,
 'ACALDtpp': -1000.0,
 '2AGPEAT140': 0.0,
 '3OAR80': -1000.0,
 '2AGPEAT141': 0.0,
 '2AGPEAT160': 0.0,
 'ACBIPGT': 0.0,
 'ACCOAC': 0.0,
 '2AGPEAT161': 0.0,
 'ACCOAL': 0.0,
 '3OAS100': 0.0,
 'ACGAL1PPpp': 0.0,
 '2AGPEAT180': 0.0,
 '2AGPEAT181': 0.0,
 '2AGPG120tipp': 0.0,
 'ACGAL1Ptex': -1000.0,
 '3OAS120': 0.0,
 'ACGALtex': -1000.0,
 'ACGAM1PPpp': 0.0,
 '2AGPG140tipp': 0.0,
 '2AGPG141tipp': 0.0,
 '2AGPG160tipp': 0.0,
 'ACGAM1Ptex': -1000.0,
 'ACGAMK': 0.0,
 'ACGAMT': 0.0,
 '2AGPG161tipp': 0.0,
 '2AGPG180tipp': 0.0,
 '2AGPG181tipp': 0.0,
 'ACGAptspp': 0.0,
 'ACGAtex': -1000.0,
 '2AGPGAT120': 0.0,
 'ACGK': 0.0,
 '2AGPGAT140': 0.0,
 '3OAS121': 0.0,
 '2AGPGAT141': 0.0,
 '2AGPGAT160': 0.0,
 'ACGS': 0.0,
 'ACHBS': 0.0,
 '3OAS140': 0.0,
 'ACKr': -1000.0,
 'ACLS': 0.0,
 '2AGPGAT161': 0.0,
 '2AGPGAT180': 0.0,
 '2AGPGAT181': 0.0,
 'ACM6PH': 0.0,
 '3OAS141': 0.0,
 'ACMAMUT': 0.0,
 '3OAS160': 0.0,
 'ACMANAptspp': 0.0,
 '3OAS161': 0.0,
 'ACMANAtex': -1000.0,
 'ACMUMtex': 0.0,
 '2DGLCNRx': 0.0,
 '2DGLCNRy': 0.0,
 '2DGULRx': 0.0,
 '2DGULRy': 0.0,
 'ACNAMt2pp': 0.0,
 'ACNAMtex': -1000.0,
 'ACNML': 0.0,
 'ACOAD1f': -1000.0,
 'ACOAD2f': -1000.0,
 '2MAHMP': 0.0,
 '3OAS180': 0.0,
 '34dhpactex': -1000.0,
 '3AMPtex': -1000.0,
 'ACOAD3f': -1000.0,
 'ACOAD4f': -1000.0,
 'ACOAD5f': -1000.0,
 '3CMPtex': -1000.0,
 '3OAS181': 0.0,
 '3GMPtex': -1000.0,
 '3HAD100': 0.0,
 '3HAD120': 0.0,
 'ACOAD6f': -1000.0,
 'ACOAD7f': -1000.0,
 'ACOAD8f': -1000.0,
 'ACOATA': -1000.0,
 '3HAD121': 0.0,
 'ACODA': 0.0,
 '3OAS60': 0.0,
 '3HAD140': 0.0,
 '3OAS80': 0.0,
 '3HAD141': 0.0,
 '3PEPTabcpp': 0.0,
 '3HAD160': 0.0,
 '3HAD161': 0.0,
 'ACOLIPAtex': 0.0,
 'ACONIs': -1000.0,
 'ACONTa': -1000.0,
 'ACONTb': -1000.0,
 'ADK1': 0.0,
 'ADK3': -1000.0,
 'ACOTA': -1000.0,
 '3PEPTtex': -1000.0,
 'ACPS1': 0.0,
 'ACS': 0.0,
 'ACSERtex': -1000.0,
 'ADK4': -1000.0,
 'ADMDC': 0.0,
 'ADNCYC': 0.0,
 '3UMPtex': -1000.0,
 'ADNK1': 0.0,
 'ADNUC': 0.0,
 'ADNt2pp_copy1': 0.0,
 'ACSERtpp': 0.0,
 'ACt2rpp': -1000.0,
 'ACt4pp': 0.0,
 'ADNt2pp_copy2': -1000.0,
 '4HOXPACDtex': -1000.0,
 'ADNtex': -1000.0,
 'ADOCBLabcpp': 0.0,
 'ACtex': -1000.0,
 'ADA': 0.0,
 'ADCL': 0.0,
 'ADOCBLtonex': 0.0,
 'ADPRDP': 0.0,
 'ADCS': 0.0,
 'ADEt2rpp': -1000.0,
 'ADEtex': -1000.0,
 'ADPT': 0.0,
 'ADSK': 0.0,
 'ADSL1r': -1000.0,
 '4PCP': 0.0,
 'ADSL2r': -1000.0,
 'ADSS': 0.0,
 'AGDC': 0.0,
 'ALDD3y': 0.0,
 'ALLTAMH': 0.0,
 'AGM3PA': 0.0,
 '4PCPpp': 0.0,
 'AGM3PApp': 0.0,
 'AGM3PH': 0.0,
 'ALLTN': 0.0,
 'ALLTNt2rpp': -1000.0,
 'AGM3Pt2pp': 0.0,
 'ALLTNtex': -1000.0,
 'AGM4PA': 0.0,
 '4PEPTabcpp': 0.0,
 'AGM4PApp': 0.0,
 'ALLtex': -1000.0,
 '4PEPTtex': -1000.0,
 'ALR2': 0.0,
 'ALR4x': 0.0,
 'AGM4PCP': 0.0,
 'AGM4PCPpp': 0.0,
 'AM3PA': 0.0,
 'AM4PA': 0.0,
 '5DGLCNR': -1000.0,
 'AM4PCP': 0.0,
 'AMALT1': 0.0,
 'AMALT2': 0.0,
 'AMALT3': 0.0,
 'AMALT4': 0.0,
 'AGM4PH': 0.0,
 'AGM4Pt2pp': 0.0,
 'AGMH': 0.0,
 'AGMHE': 0.0,
 'AGMT': 0.0,
 'AGMt2pp': 0.0,
 'AMANAPEr': -1000.0,
 'AMANK': 0.0,
 'AMAOTr': -1000.0,
 'AGMtex': -1000.0,
 '5DGLCNt2rpp': -1000.0,
 'AGPAT120': 0.0,
 'AGPAT140': 0.0,
 'AMMQLT8': 0.0,
 'AMPMS2': 0.0,
 '5DGLCNtex': -1000.0,
 'AMPN': 0.0,
 'AMPTASECG': 0.0,
 'AMPTASEPG': 0.0,
 'AGPAT141': 0.0,
 'AGPAT160': 0.0,
 'AGPAT161': 0.0,
 'AMPtex': -1000.0,
 '5DOAN': 0.0,
 'ANHGMtex': -1000.0,
 'ANHMK': 0.0,
 'AGPAT180': 0.0,
 'AGPAT181': 0.0,
 'AGPR': -1000.0,
 'AHCYSNS': 0.0,
 'ANPRT': 0.0,
 'ANS': 0.0,
 'AOBUTDs': 0.0,
 'AOXSr': -1000.0,
 'AP4AH': 0.0,
 'AICART': -1000.0,
 'AIRC2': 0.0,
 'AP5AH': 0.0,
 'A5PISO': -1000.0,
 'APRAUR': 0.0,
 'AIRC3': -1000.0,
 'AKGDH': 0.0,
 'ARAI': -1000.0,
 'AACPS1': 0.0,
 'ARBTNR1': 0.0,
 'ARBTNR2': 0.0,
 'AKGt2rpp': -1000.0,
 'AKGtex': -1000.0,
 'ARBTNR3': 0.0,
 'ALAALAabcpp': 0.0,
 'AACPS2': 0.0,
 'ALAALAr': 0.0,
 'ALAALAtex': -1000.0,
 'ARBTNabcpp': 0.0,
 'ARBTNexs': 0.0,
 'ARBTNtex': 0.0,
 'ALAGLUE': -1000.0,
 'ALAR': -1000.0,
 'ALATA_D2': 0.0,
 'AACPS3': 0.0,
 'ALATA_L': -1000.0,
 'ALATA_L2': 0.0,
 'ALATRS': 0.0,
 'ALAabcpp': 0.0,
 'ARBTNtonex': 0.0,
 'ARBTNtpp': 0.0,
 'ARBt2rpp': -1000.0,
 'ARBt3ipp': 0.0,
 'ARBtex': -1000.0,
 'ARGAGMt7pp': -1000.0,
 'ALAt2pp': 0.0,
 'ALAt4pp': 0.0,
 'ARGDC': 0.0,
 'AACPS4': 0.0,
 'ARGDCpp': 0.0,
 'ARGORNt7pp': -1000.0,
 'ALAtex': -1000.0,
 'ALDD2y': 0.0,
 'ARGSL': -1000.0,
 'AACPS5': 0.0,
 'ARGSS': 0.0,
 'ARGTRS': 0.0,
 'ASNNpp': 0.0,
 'AACPS6': 0.0,
 'ASNS1': 0.0,
 'ARGabcpp': 0.0,
 'ARGt3pp': 0.0,
 'ASNS2': 0.0,
 'AACPS7': 0.0,
 'ARGtex': -1000.0,
 'ASAD': -1000.0,
 'AACPS8': 0.0,
 'ASCBPL': 0.0,
 'ASCBptspp': 0.0,
 'ASCBtex': -1000.0,
 'AACPS9': 0.0,
 'ASNN': 0.0,
 'AACTOOR': 0.0,
 'AAMYL': 0.0,
 'ASNTRS_1': 0.0,
 'AAMYLpp': 0.0,
 'ASNabcpp': 0.0,
 'ABTA': 0.0,
 'ASNt2rpp': -1000.0,
 'ABUTD': 0.0,
 'ASNtex': -1000.0,
 'ASO3tex': -1000.0,
 'ABUTt2pp': 0.0,
 'ASP1DC': 0.0,
 'CRNDCAL2': 0.0,
 'ASPCT': 0.0,
 'ASPK': -1000.0,
 'ASPO3': 0.0,
 'ASPO4': 0.0,
 'ASPO5': 0.0,
 'ASPO6': 0.0,
 'CDPMEK': 0.0,
 'CFAS160E': 0.0,
 'CFAS160G': 0.0,
 'CFAS180E': 0.0,
 'CRNDabcpp': 0.0,
 'CFAS180G': 0.0,
 'CGLYabcpp': 0.0,
 'ASPT': 0.0,
 'ASPTA': -1000.0,
 'CGLYtex': -1000.0,
 'CHLabcpp': 0.0,
 'CHLtex': -1000.0,
 'ASPTRS': 0.0,
 'ASPabcpp': 0.0,
 'ASPt2_2pp': 0.0,
 'ASPt2pp': 0.0,
 'CHORS': 0.0,
 'CHRPL': 0.0,
 'ASPtex': -1000.0,
 'AST': 0.0,
 'CITL': 0.0,
 'CRNDt2rpp': -1000.0,
 'CITt7pp': 0.0,
 'CITtex': -1000.0,
 'ATHRDHr': -1000.0,
 'ATPHs': 0.0,
 'ATPM': 8.39,
 'CRNabcpp': 0.0,
 'ATPPRT': 0.0,
 'CRNt2rpp': -1000.0,
 'ATPS4rpp': -1000.0,
 'ICITtex': -1000.0,
 'CRNt7pp': 0.0,
 'ACONCtex': -1000.0,
 'BALAt2pp': 0.0,
 'BALAtex': -1000.0,
 'CRNt8pp': 0.0,
 'BPNT': 0.0,
 'BSORx': 0.0,
 'BSORy': 0.0,
 'BTS4': 0.0,
 'BUTSO3tex': -1000.0,
 'CLIPAtex': 0.0,
 'CLPNH120pp': 0.0,
 'CLPNH140pp': 0.0,
 'CLPNH141pp': 0.0,
 'CLPNH160pp': 0.0,
 'CLPNH161pp': 0.0,
 'CLPNH180pp': 0.0,
 'BUTtex': -1000.0,
 'CLPNH181pp': 0.0,
 'CRNtex': -1000.0,
 'CLPNS120pp': -1000.0,
 'CA2t3pp': 0.0,
 'CS': 0.0,
 'CA2tex': -1000.0,
 'CADVtpp': 0.0,
 'CLPNS140pp': -1000.0,
 'CLPNS141pp': -1000.0,
 'CAt6pp': -1000.0,
 'CLPNS160pp': -1000.0,
 'CSNtex': -1000.0,
 'CLPNS161pp': -1000.0,
 'CLPNS180pp': -1000.0,
 'CBIAT': -1000.0,
 'CBItonex': 0.0,
 'CBIuabcpp': 0.0,
 'CBL1abcpp': 0.0,
 'CLPNS181pp': -1000.0,
 'CTBTCAL2': 0.0,
 'CLt3_2pp': 0.0,
 'CLtex': -1000.0,
 'CMPN': 0.0,
 'CMPtex': -1000.0,
 'CBL1tonex': 0.0,
 'CBPS': 0.0,
 'CD2abcpp': 0.0,
 'CD2t3pp': 0.0,
 'CD2tex': -1000.0,
 'CD2tpp': 0.0,
 'CDAPPA120': 0.0,
 'CO2tex': -1000.0,
 'CO2tpp': -1000.0,
 'CDAPPA140': 0.0,
 'CTBTabcpp': 0.0,
 'CDAPPA141': 0.0,
 'CDAPPA160': 0.0,
 'COBALT2abcpp': 0.0,
 'COBALT2t3pp': 0.0,
 'COBALT2tex': -1000.0,
 'CTBTt2rpp': -1000.0,
 'COBALT2tpp_copy1': 0.0,
 'COLIPAabcpp': 0.0,
 'COLIPAtex': 0.0,
 'CDAPPA161': 0.0,
 'CDAPPA180': 0.0,
 'CDAPPA181': 0.0,
 'CPGNR1': 0.0,
 'CTPS2': 0.0,
 'CPGNR2': 0.0,
 'CPGNR3': 0.0,
 'CU1Opp': 0.0,
 'CPGNUtex': 0.0,
 'CPGNUtpp': 0.0,
 'CPGNabcpp': 0.0,
 'CPGNexs': 0.0,
 'DAMPtex': -1000.0,
 'DAPDC': 0.0,
 'DAPE': -1000.0,
 'DAPabcpp': 0.0,
 'DAPtex': -1000.0,
 'CPGNtonex': 0.0,
 'CU1abcpp': 0.0,
 'CPPPGO': 0.0,
 'CPPPGO2': 0.0,
 'DASYN120': 0.0,
 'DASYN140': 0.0,
 'CRNBTCT': -1000.0,
 'AU1abcpp': 0.0,
 'CRNCAL2': 0.0,
 'CRNCAR': -1000.0,
 'CRNCBCT': -1000.0,
 'DASYN141': 0.0,
 'DASYN160': 0.0,
 'DASYN161': 0.0,
 'DASYN180': 0.0,
 'CRNCDH': -1000.0,
 'CU2abcpp': 0.0,
 'DASYN181': 0.0,
 'DATPHs': 0.0,
 'CU2tex': -1000.0,
 'DB4PS': 0.0,
 'DBTS': 0.0,
 'DMQMT': 0.0,
 'CU2tpp': 0.0,
 'DMSOtex': -1000.0,
 'DMStex': -1000.0,
 'DM_4hba_c': 0.0,
 'DCAtex': -1000.0,
 'DCMPtex': -1000.0,
 'DCTPD': 0.0,
 'DCYTD': 0.0,
 'DCYTt2pp': 0.0,
 'CUtex': -1000.0,
 'DCYTtex': -1000.0,
 'DDCAtexi': 0.0,
 'DDGALK': 0.0,
 'DM_5drib_c': 0.0,
 'DM_hmfurn_c': 0.0,
 'DM_oxam_c': 0.0,
 'DNMPPA': 0.0,
 'DNTPPA': 0.0,
 'DDGLCNtex': -1000.0,
 'CYANST': 0.0,
 'DDGLK': 0.0,
 'DDPA': 0.0,
 'DGK1': -1000.0,
 'DOGULNR': 0.0,
 'DOPAtex': -1000.0,
 'DPCOAK': 0.0,
 'DRPA': 0.0,
 'DGMPtex': -1000.0,
 'DGSNt2pp': 0.0,
 'CYANSTpp': 0.0,
 'DGSNtex': -1000.0,
 'DSBAO1': 0.0,
 'DSBAO2': 0.0,
 'DSBCGT': 0.0,
 'DSBDR': 0.0,
 'DSBGGT': 0.0,
 'DHAD1': 0.0,
 'DHAD2': 0.0,
 'DHAtex': -1000.0,
 'DHAtpp': -1000.0,
 'DHBD': 0.0,
 'DSERDHr': -1000.0,
 'DSERt2pp': 0.0,
 'DSERtex': -1000.0,
 'DHBS': 0.0,
 'CYANtex': -1000.0,
 'DHDPRy': 0.0,
 'DHDPS': 0.0,
 'DTMPK': -1000.0,
 'DTMPtex': -1000.0,
 'CYNTtex': -1000.0,
 'DUMPtex': -1000.0,
 'DURIK1': 0.0,
 'DURIPP': -1000.0,
 'DHFR': -1000.0,
 'DHFS': 0.0,
 'DHNAOT4': 0.0,
 'DURIt2pp': 0.0,
 'DURItex': -1000.0,
 'DHNPA2r': 0.0,
 'DUTPDP': 0.0,
 'DHORD2': 0.0,
 'CYSDS_copy1': 0.0,
 'DHORD5': 0.0,
 'DHORTS': -1000.0,
 'DXPRIi': 0.0,
 'DXPS': 0.0,
 'DXYLK': 0.0,
 'DHPPDA2': 0.0,
 'DHPS2': 0.0,
 'CYSDtex': -1000.0,
 'DHPTDCs': 0.0,
 'D_LACt2pp': -1000.0,
 'D_LACtex': -1000.0,
 'DHQS': 0.0,
 'DHQTi': 0.0,
 'E4PD': 0.0,
 'CYSS': 0.0,
 'EAR100x': 0.0,
 'EAR100y': 0.0,
 'DIMPtex': -1000.0,
 'DINSt2pp': 0.0,
 'EAR120x': 0.0,
 'DINStex': -1000.0,
 'EAR120y': 0.0,
 'CYSSADS': 0.0,
 'EAR121x': 0.0,
 'EAR121y': 0.0,
 'DKGLCNR1': 0.0,
 'DKGLCNR2x': 0.0,
 'EAR140x': 0.0,
 'DKGLCNR2y': 0.0,
 'CYSTL': 0.0,
 'DKMPPD': 0.0,
 'EAR140y': 0.0,
 'EAR141x': 0.0,
 'DKMPPD3': 0.0,
 'DMATT': 0.0,
 'DMPPS': 0.0,
 'EAR141y': 0.0,
 'EAR160x': 0.0,
 'EAR160y': 0.0,
 'EAR161x': 0.0,
 'CYSTRS': 0.0,
 'EAR161y': 0.0,
 'EAR180x': 0.0,
 'EAR180y': 0.0,
 'EAR181x': 0.0,
 'EX_alaala_e': 0.0,
 'EAR181y': 0.0,
 'ECAP3pp': 0.0,
 'CYSabc2pp': 0.0,
 'ECAtpp': 0.0,
 'ECOAH1': -1000.0,
 'EAR40x': 0.0,
 'EAR40y': 0.0,
 'EAR60x': 0.0,
 'EAR60y': 0.0,
 'ECOAH2': -1000.0,
 'CYSabcpp': 0.0,
 'ECOAH3': -1000.0,
 'ECOAH4': -1000.0,
 'EAR80x': 0.0,
 'EAR80y': 0.0,
 'ECA4COLIPAtex': 0.0,
 'ECOAH5': -1000.0,
 'CYSIabcpp': 0.0,
 'ECOAH6': -1000.0,
 'ECA4OALpp': 0.0,
 'ECAP1pp': 0.0,
 'ECAP2pp': 0.0,
 'ECOAH7': -1000.0,
 'ECOAH8': -1000.0,
 'EDA': 0.0,
 'CYStex': -1000.0,
 'EDD': 0.0,
 'EDTXS1': 0.0,
 'CYSItex': -1000.0,
 'EDTXS2': 0.0,
 'EDTXS3': 0.0,
 'CYStpp': 0.0,
 'EDTXS4': 0.0,
 'ENLIPAtex': 0.0,
 'CYTBO3_4pp': 0.0,
 'EX_all__D_e': 0.0,
 'ENO': -1000.0,
 'CYTD': 0.0,
 'CYTDH': 0.0,
 'CYTDK2': 0.0,
 'ENTCS': 0.0,
 'ETHAAL': 0.0,
 'EX_alltn_e': 0.0,
 'EX_amp_e': 0.0,
 'CYTDt2pp_copy1': 0.0,
 'EX_anhgm_e': 0.0,
 'EX_arab__L_e': 0.0,
 'ETHAt2pp': 0.0,
 'ETHAtex': -1000.0,
 'ETHSO3tex': -1000.0,
 'ETOHt2rpp': -1000.0,
 'CYTDt2pp_copy2': -1000.0,
 'ETOHtex': -1000.0,
 'EX_arbtn_e': 0.0,
 'CYTDtex': -1000.0,
 'EX_arbtn_fe3_e': 0.0,
 'EX_chitob_e': 0.0,
 'CYTK1': -1000.0,
 'EX_pydxn_e': 0.0,
 'EX_pydx_e': 0.0,
 'EX_arg__L_e': 0.0,
 'EX_ascb__L_e': 0.0,
 'EX_asn__L_e': 0.0,
 'EX_12ppd__R_e': 0.0,
 'CYTK2': -1000.0,
 'EX_aso3_e': 0.0,
 'EX_asp__L_e': 0.0,
 'EX_12ppd__S_e': 0.0,
 'EX_but_e': 0.0,
 'DAAD': 0.0,
 'EX_14glucan_e': 0.0,
 'EX_15dap_e': 0.0,
 'EX_butso3_e': 0.0,
 'DADA': 0.0,
 'EX_ca2_e': -1000.0,
 'EX_cbi_e': 0.0,
 'EX_cbl1_e': -0.01,
 'EX_23camp_e': 0.0,
 'EX_23ccmp_e': 0.0,
 'EX_23cgmp_e': 0.0,
 'EX_cd2_e': 0.0,
 'EX_23cump_e': 0.0,
 'DADK': -1000.0,
 'EX_23dappa_e': 0.0,
 'EX_26dap__M_e': 0.0,
 'EX_cgly_e': 0.0,
 'EX_chol_e': 0.0,
 'EX_cit_e': 0.0,
 'EX_2ddglcn_e': 0.0,
 'DADNt2pp': 0.0,
 'EX_34dhpac_e': 0.0,
 'EX_3amp_e': 0.0,
 'EX_3cmp_e': 0.0,
 'EX_3gmp_e': 0.0,
 'EX_icit_e': 0.0,
 'EX_acon_C_e': 0.0,
 'EX_cl_e': -1000.0,
 'EX_cmp_e': 0.0,
 'EX_co2_e': -1000.0,
 'DADNtex': -1000.0,
 'EX_cobalt2_e': -1000.0,
 'EX_colipa_e': 0.0,
 'EX_3hcinnm_e': 0.0,
 'DAGK120': 0.0,
 'EX_3hpppn_e': 0.0,
 'EX_cpgn_e': 0.0,
 'EX_cpgn_un_e': 0.0,
 'DAGK140': 0.0,
 'EX_crn_e': 0.0,
 'EX_3ump_e': 0.0,
 'EX_csn_e': 0.0,
 'DAGK141': 0.0,
 'EX_cu2_e': -1000.0,
 'EX_cu_e': 0.0,
 'EX_4abut_e': 0.0,
 'EX_4hoxpacd_e': 0.0,
 'EX_5dglcn_e': 0.0,
 'EX_cyan_e': 0.0,
 'EX_LalaDgluMdapDala_e': 0.0,
 'DAGK160': 0.0,
 'EX_LalaDgluMdap_e': 0.0,
 'EX_ac_e': 0.0,
 'EX_cynt_e': 0.0,
 'EX_cys__D_e': 0.0,
 'EX_cys__L_e': 0.0,
 'EX_acac_e': 0.0,
 'EX_acald_e': 0.0,
 'DAGK161': 0.0,
 'EX_acgal1p_e': 0.0,
 'EX_acgal_e': 0.0,
 'EX_cysi__L_e': 0.0,
 'EX_cytd_e': 0.0,
 'EX_dad_2_e': 0.0,
 'EX_damp_e': 0.0,
 'EX_dca_e': 0.0,
 'EX_dcmp_e': 0.0,
 'EX_acgam1p_e': 0.0,
 'EX_acgam_e': 0.0,
 'EX_acmana_e': 0.0,
 'DAGK180': 0.0,
 'EX_acmum_e': 0.0,
 'EX_acnam_e': 0.0,
 'EX_acolipa_e': 0.0,
 'EX_dcyt_e': 0.0,
 'EX_ddca_e': 0.0,
 'DAGK181': 0.0,
 'EX_dgmp_e': 0.0,
 'EX_dgsn_e': 0.0,
 'EX_acser_e': 0.0,
 'EX_ade_e': 0.0,
 'EX_adn_e': 0.0,
 'EX_adocbl_e': 0.0,
 'EX_dha_e': 0.0,
 'EX_dimp_e': 0.0,
 'DALAt2pp': 0.0,
 'EX_din_e': 0.0,
 'EX_ag_e': 0.0,
 'EX_agm_e': 0.0,
 'EX_dms_e': 0.0,
 'DALAtex': -1000.0,
 'EX_dmso_e': 0.0,
 'EX_akg_e': 0.0,
 'EX_ala_B_e': 0.0,
 'EX_ala__D_e': 0.0,
 'EX_dopa_e': 0.0,
 'EX_g1p_e': 0.0,
 'EX_dtmp_e': 0.0,
 'EX_dump_e': 0.0,
 'EX_duri_e': 0.0,
 'EX_eca4colipa_e': 0.0,
 'EX_enlipa_e': 0.0,
 'EX_enter_e': 0.0,
 'EX_etha_e': 0.0,
 'EX_ala__L_e': 0.0,
 'EX_melib_e': 0.0,
 'EX_met__D_e': 0.0,
 'EX_met__L_e': 0.0,
 'EX_metsox_R__L_e': 0.0,
 'EX_metsox_S__L_e': 0.0,
 'EX_mg2_e': -1000.0,
 'EX_ethso3_e': 0.0,
 'EX_etoh_e': 0.0,
 'EX_minohp_e': 0.0,
 'EX_f6p_e': 0.0,
 'EX_g3pc_e': 0.0,
 'EX_fald_e': 0.0,
 'EX_fe2_e': -1000.0,
 'EX_fe3_e': -1000.0,
 'EX_fe3dcit_e': 0.0,
 'EX_mmet_e': 0.0,
 'EX_mn2_e': -1000.0,
 'EX_mnl_e': 0.0,
 'EX_fe3dhbzs_e': 0.0,
 'EX_mobd_e': -1000.0,
 'EX_g3pe_e': 0.0,
 'EX_mso3_e': 0.0,
 'EX_fe3hox_e': 0.0,
 'EX_fe3hox_un_e': 0.0,
 'EX_fecrm_e': 0.0,
 'EX_n2o_e': 0.0,
 'EX_g3pg_e': 0.0,
 'EX_na1_e': -1000.0,
 'EX_fecrm_un_e': 0.0,
 'EX_feenter_e': 0.0,
 'EX_nac_e': 0.0,
 'EX_feoxam_e': 0.0,
 'EX_g3pi_e': 0.0,
 'EX_feoxam_un_e': 0.0,
 'EX_nh4_e': -1000.0,
 'EX_ni2_e': 0.0,
 'EX_for_e': 0.0,
 'EX_fru_e': 0.0,
 'EX_frulys_e': 0.0,
 'EX_fruur_e': 0.0,
 'EX_nmn_e': 0.0,
 'EX_no2_e': 0.0,
 'EX_no3_e': 0.0,
 'EX_no_e': 0.0,
 'EX_g3ps_e': 0.0,
 'EX_o2_e': -18.5,
 'EX_o2s_e': 0.0,
 'EX_fuc__L_e': 0.0,
 'EX_fum_e': 0.0,
 'EX_ocdca_e': 0.0,
 'EX_g6p_e': 0.0,
 'EX_ocdcea_e': 0.0,
 'EX_octa_e': 0.0,
 'EX_gal1p_e': 0.0,
 'EX_orn_e': 0.0,
 'EX_orot_e': 0.0,
 'EX_udpgal_e': 0.0,
 'EX_udpglcur_e': 0.0,
 'EX_gal_bD_e': 0.0,
 'EX_ump_e': 0.0,
 'EX_gal_e': 0.0,
 'EX_ura_e': 0.0,
 'EX_urea_e': 0.0,
 'EX_oaa_e': 0.0,
 'EX_pacald_e': 0.0,
 'EX_peamn_e': 0.0,
 'EX_galct__D_e': 0.0,
 'EX_phe__L_e': 0.0,
 'EX_pheme_e': 0.0,
 'EX_uri_e': 0.0,
 'EX_pi_e': -1000.0,
 'EX_galctn__D_e': 0.0,
 'EX_val__L_e': 0.0,
 'EX_xan_e': 0.0,
 'EX_pnto__R_e': 0.0,
 'EX_galctn__L_e': 0.0,
 'EX_ppa_e': 0.0,
 'EX_xmp_e': 0.0,
 'EX_xtsn_e': 0.0,
 'EX_xyl__D_e': 0.0,
 'EX_xylu__L_e': 0.0,
 'EX_zn2_e': -1000.0,
 'EX_ppal_e': 0.0,
 'EX_pppn_e': 0.0,
 'EX_ppt_e': 0.0,
 'EX_pro__L_e': 0.0,
 'BIOMASS_Ec_iAF1260_core_59p81M': 0.0,
 'EX_progly_e': 0.0,
 'EX_galt_e': 0.0,
 'EX_psclys_e': 0.0,
 'EX_pser__L_e': 0.0,
 'F6PA': -1000.0,
 'F6PP': 0.0,
 'F6Pt6_2pp': 0.0,
 'EX_ptrc_e': 0.0,
 'EX_galur_e': 0.0,
 'EX_pyr_e': 0.0,
 'F6Ptex': -1000.0,
 'FA100ACPHi': 0.0,
 'FA120ACPHi': 0.0,
 'EX_r5p_e': 0.0,
 'EX_gam6p_e': 0.0,
 'EX_rib__D_e': 0.0,
 'EX_rmn_e': 0.0,
 'FA140ACPHi': 0.0,
 'FA141ACPHi': 0.0,
 'FA160ACPHi': 0.0,
 'EX_sbt__D_e': 0.0,
 'EX_gam_e': 0.0,
 'EX_ser__D_e': 0.0,
 'FA161ACPHi': 0.0,
 'FA80ACPHi': 0.0,
 'FACOAE100': 0.0,
 'EX_ser__L_e': 0.0,
 'EX_gbbtn_e': 0.0,
 'EX_skm_e': 0.0,
 'EX_so2_e': 0.0,
 'EX_so3_e': 0.0,
 'EX_so4_e': -1000.0,
 'FACOAE120': 0.0,
 'FACOAE140': 0.0,
 'FACOAE141': 0.0,
 'FACOAE160': 0.0,
 'FACOAE161': 0.0,
 'FACOAE180': 0.0,
 'EX_spmd_e': 0.0,
 'EX_succ_e': 0.0,
 'FACOAE181': 0.0,
 'EX_sucr_e': 0.0,
 'FACOAE60': 0.0,
 'EX_gdp_e': 0.0,
 'FACOAE80': 0.0,
 'FACOAL100t2pp': 0.0,
 'EX_sulfac_e': 0.0,
 'EX_tartr__L_e': 0.0,
 'EX_taur_e': 0.0,
 'EX_tcynt_e': 0.0,
 'FACOAL120t2pp': 0.0,
 'EX_glc__D_e': -5.0,
 'FACOAL140t2pp': 0.0,
 'EX_thm_e': 0.0,
 'EX_thr__L_e': 0.0,
 'FACOAL141t2pp': 0.0,
 'EX_glcn_e': 0.0,
 'FACOAL160t2pp': 0.0,
 'EX_thrp_e': 0.0,
 'EX_thym_e': 0.0,
 'EX_glcr_e': 0.0,
 'EX_thymd_e': 0.0,
 'EX_tma_e': 0.0,
 'FACOAL161t2pp': 0.0,
 'FACOAL180t2pp': 0.0,
 'FACOAL181t2pp': 0.0,
 'FACOAL60t2pp': 0.0,
 'FACOAL80t2pp': 0.0,
 'EX_tmao_e': 0.0,
 'EX_tre_e': 0.0,
 'EX_trp__L_e': 0.0,
 'EX_tsul_e': 0.0,
 'EX_ttdca_e': 0.0,
 'FADRx_copy1': 0.0,
 'EX_ttdcea_e': 0.0,
 'EX_glcur1p_e': 0.0,
 'EX_tungs_e': -1000.0,
 'EX_tym_e': 0.0,
 'FADRx2': 0.0,
 'FALDtex': -1000.0,
 'FALDtpp': -1000.0,
 'EX_tyr__L_e': 0.0,
 'EX_glcur_e': 0.0,
 'EX_tyrp_e': 0.0,
 'EX_uacgam_e': 0.0,
 'FALGTHLs': -1000.0,
 'FBA': -1000.0,
 'EX_udpacgal_e': 0.0,
 'EX_gln__L_e': 0.0,
 'EX_udpg_e': 0.0,
 'FBP': 0.0,
 'FCI': -1000.0,
 'FCLK': 0.0,
 'EX_glu__L_e': 0.0,
 'FCLPA': -1000.0,
 'EX_gly_e': 0.0,
 'FCLT': 0.0,
 'FDH4pp': 0.0,
 'FE3DHBZStonex': 0.0,
 'FE3HOXR1': 0.0,
 'FE3HOXR2': 0.0,
 'FE3HOXR3': 0.0,
 'FE3HOXUtex': 0.0,
 'FDH5pp': 0.0,
 'FE2t2pp': 0.0,
 'FE2tex': -1000.0,
 'FE2tpp': 0.0,
 'FE3HOXUtpp': 0.0,
 'FE3HOXexs': 0.0,
 'EX_glyald_e': 0.0,
 'FE3HOXtonex': 0.0,
 'FE3Ri': 0.0,
 'FE3DHBZR': 0.0,
 'FE3DHBZSabcpp': 0.0,
 'FE3tex': -1000.0,
 'G1PPpp': 0.0,
 'EX_glyb_e': 0.0,
 'FECRMR1': 0.0,
 'FECRMR2': 0.0,
 'FECRMR3': 0.0,
 'G1PTT': 0.0,
 'EX_glyc2p_e': 0.0,
 'G1Ptex': -1000.0,
 'FECRMUtex': 0.0,
 'FECRMUtpp': 0.0,
 'FECRMabcpp': 0.0,
 'EX_glyc3p_e': 0.0,
 'FECRMexs': 0.0,
 'G1SAT': -1000.0,
 'G2PPpp': 0.0,
 'FECRMtonex': 0.0,
 'EX_glyc__R_e': 0.0,
 'FEENTERabcpp': 0.0,
 'FEENTERexs': 0.0,
 'FEENTERtonex': 0.0,
 'G3PAT120': 0.0,
 'G3PAT140': 0.0,
 'EX_glyc_e': 0.0,
 'EX_glyclt_e': 0.0,
 'G3PAT141': 0.0,
 'FEENTERtpp': 0.0,
 'EX_gmp_e': 0.0,
 'G3PAT160': 0.0,
 'G3PAT161': 0.0,
 'FEOXAMUtex': 0.0,
 'EX_gsn_e': 0.0,
 'FEOXAMUtpp': 0.0,
 'FEOXAMabcpp': 0.0,
 'FEOXAMexs': 0.0,
 'G3PAT180': 0.0,
 'G3PAT181': 0.0,
 'FEOXAMtonex': 0.0,
 'EX_gthox_e': 0.0,
 'FEROpp': 0.0,
 'G3PCabcpp': 0.0,
 'EX_gthrd_e': 0.0,
 'G3PCtex': -1000.0,
 'FHL': 0.0,
 'FLDR': 0.0,
 'EX_gtp_e': 0.0,
 'FLVR': 0.0,
 'G3PD2': -1000.0,
 'G3PD5': 0.0,
 'G3PD6': 0.0,
 ...}

In [31]:
for rx2 in stm1585_model.reactions:
    rx1_lower = lower_bounds[rx2.id]
    rx1_upper = upper_bounds[rx2.id]
    if 1 or rx2.lower_bound != rx1_lower or rx2.upper_bound != rx1_upper:
        print(rx2.id, rx2.lower_bound, rx1_lower, rx2.upper_bound, rx1_upper)

3HAD180 0.0 0.0 1000.0 1000.0
3HAD181 0.0 0.0 1000.0 1000.0
3HAD40 0.0 0.0 1000.0 1000.0
3HAD60 0.0 0.0 1000.0 1000.0
3HAD80 0.0 0.0 1000.0 1000.0
3KGK 0.0 0.0 1000.0 1000.0
3NTD2pp 0.0 0.0 1000.0 1000.0
3NTD4pp 0.0 0.0 1000.0 1000.0
3NTD7pp 0.0 0.0 1000.0 1000.0
3NTD9pp 0.0 0.0 1000.0 1000.0
3OAR100 -1000.0 -1000.0 1000.0 1000.0
3OAR120 -1000.0 -1000.0 1000.0 1000.0
3OAR121 0.0 0.0 1000.0 1000.0
3OAR140 -1000.0 -1000.0 1000.0 1000.0
3OAR141 0.0 0.0 1000.0 1000.0
3OAR160 -1000.0 -1000.0 1000.0 1000.0
3OAR161 0.0 0.0 1000.0 1000.0
23CAMPtex -1000.0 -1000.0 1000.0 1000.0
23CCMPtex -1000.0 -1000.0 1000.0 1000.0
23CGMPtex -1000.0 -1000.0 1000.0 1000.0
12DGR120tipp 0.0 0.0 1000.0 1000.0
12DGR140tipp 0.0 0.0 1000.0 1000.0
12DGR141tipp 0.0 0.0 1000.0 1000.0
12DGR160tipp 0.0 0.0 1000.0 1000.0
23CUMPtex -1000.0 -1000.0 1000.0 1000.0
3OAR180 -1000.0 -1000.0 1000.0 1000.0
23DAPPAt2pp 0.0 0.0 1000.0 1000.0
23DAPPAtex -1000.0 -1000.0 1000.0 1000.0
12DGR161tipp 0.0 0.0 1000.0 1000.0
12DGR180tipp 0.0 0.0 1000.0 1000.0
12DGR181tipp 0.0 0.0 1000.0 1000.0
12PPDRtex -1000.0 -1000.0 1000.0 1000.0
12PPDRtpp -1000.0 -1000.0 1000.0 1000.0
12PPDStex -1000.0 -1000.0 1000.0 1000.0
12PPDStpp -1000.0 -1000.0 1000.0 1000.0
23PDE2pp 0.0 0.0 1000.0 1000.0
23PDE4pp 0.0 0.0 1000.0 1000.0
23PDE7pp 0.0 0.0 1000.0 1000.0
23PDE9pp 0.0 0.0 1000.0 1000.0
26DAHtex -1000.0 -1000.0 1000.0 1000.0
2AGPA120tipp 0.0 0.0 1000.0 1000.0
2AGPA140tipp 0.0 0.0 1000.0 1000.0
2AGPA141tipp 0.0 0.0 1000.0 1000.0
2AGPA160tipp 0.0 0.0 1000.0 1000.0
2AGPA161tipp 0.0 0.0 1000.0 1000.0
2AGPA180tipp 0.0 0.0 1000.0 1000.0
2AGPA181tipp 0.0 0.0 1000.0 1000.0
14GLUCANabcpp 0.0 0.0 1000.0 1000.0
14GLUCANtexi 0.0 0.0 1000.0 1000.0
2AGPE120tipp 0.0 0.0 1000.0 1000.0
3OAR181 0.0 0.0 1000.0 1000.0
2AGPE140tipp 0.0 0.0 1000.0 1000.0
2AGPE141tipp 0.0 0.0 1000.0 1000.0
3OAR40 -1000.0 -1000.0 1000.0 1000.0
2AGPE160tipp 0.0 0.0 1000.0 1000.0
3OAR60 -1000.0 -1000.0 1000.0 1000.0
2AGPE161tipp 0.0 0.0 1000.0 1000.0
2AGPE180tipp 0.0 0.0 1000.0 1000.0
2AGPE181tipp 0.0 0.0 1000.0 1000.0
2AGPEAT120 0.0 0.0 1000.0 1000.0
ABUTtex -1000.0 -1000.0 1000.0 1000.0
ACACtex -1000.0 -1000.0 1000.0 1000.0
ACALD -1000.0 -1000.0 1000.0 1000.0
ACALDtex -1000.0 -1000.0 1000.0 1000.0
ACALDtpp -1000.0 -1000.0 1000.0 1000.0
2AGPEAT140 0.0 0.0 1000.0 1000.0
3OAR80 -1000.0 -1000.0 1000.0 1000.0
2AGPEAT141 0.0 0.0 1000.0 1000.0
2AGPEAT160 0.0 0.0 1000.0 1000.0
ACBIPGT 0.0 0.0 1000.0 1000.0
ACCOAC 0.0 0.0 1000.0 1000.0
2AGPEAT161 0.0 0.0 1000.0 1000.0
ACCOAL 0.0 0.0 1000.0 1000.0
3OAS100 0.0 0.0 1000.0 1000.0
ACGAL1PPpp 0.0 0.0 1000.0 1000.0
2AGPEAT180 0.0 0.0 1000.0 1000.0
2AGPEAT181 0.0 0.0 1000.0 1000.0
2AGPG120tipp 0.0 0.0 1000.0 1000.0
ACGAL1Ptex -1000.0 -1000.0 1000.0 1000.0
3OAS120 0.0 0.0 1000.0 1000.0
ACGALtex -1000.0 -1000.0 1000.0 1000.0
ACGAM1PPpp 0.0 0.0 1000.0 1000.0
2AGPG140tipp 0.0 0.0 1000.0 1000.0
2AGPG141tipp 0.0 0.0 1000.0 1000.0
2AGPG160tipp 0.0 0.0 1000.0 1000.0
ACGAM1Ptex -1000.0 -1000.0 1000.0 1000.0
ACGAMK 0.0 0.0 1000.0 1000.0
ACGAMT 0.0 0.0 1000.0 1000.0
2AGPG161tipp 0.0 0.0 1000.0 1000.0
2AGPG180tipp 0.0 0.0 1000.0 1000.0
2AGPG181tipp 0.0 0.0 1000.0 1000.0
ACGAptspp 0.0 0.0 1000.0 1000.0
ACGAtex -1000.0 -1000.0 1000.0 1000.0
2AGPGAT120 0.0 0.0 1000.0 1000.0
ACGK 0.0 0.0 1000.0 1000.0
2AGPGAT140 0.0 0.0 1000.0 1000.0
3OAS121 0.0 0.0 1000.0 1000.0
2AGPGAT141 0.0 0.0 1000.0 1000.0
2AGPGAT160 0.0 0.0 1000.0 1000.0
ACGS 0.0 0.0 1000.0 1000.0
ACHBS 0.0 0.0 1000.0 1000.0
3OAS140 0.0 0.0 1000.0 1000.0
ACKr -1000.0 -1000.0 1000.0 1000.0
ACLS 0.0 0.0 1000.0 1000.0
2AGPGAT161 0.0 0.0 1000.0 1000.0
2AGPGAT180 0.0 0.0 1000.0 1000.0
2AGPGAT181 0.0 0.0 1000.0 1000.0
ACM6PH 0.0 0.0 1000.0 1000.0
3OAS141 0.0 0.0 1000.0 1000.0
ACMAMUT 0.0 0.0 1000.0 1000.0
3OAS160 0.0 0.0 1000.0 1000.0
ACMANAptspp 0.0 0.0 1000.0 1000.0
3OAS161 0.0 0.0 1000.0 1000.0
ACMANAtex -1000.0 -1000.0 1000.0 1000.0
ACMUMtex 0.0 0.0 1000.0 1000.0
2DGLCNRx 0.0 0.0 1000.0 1000.0
2DGLCNRy 0.0 0.0 1000.0 1000.0
2DGULRx 0.0 0.0 1000.0 1000.0
2DGULRy 0.0 0.0 1000.0 1000.0
ACNAMt2pp 0.0 0.0 1000.0 1000.0
ACNAMtex -1000.0 -1000.0 1000.0 1000.0
ACNML 0.0 0.0 1000.0 1000.0
ACOAD1f -1000.0 -1000.0 1000.0 1000.0
ACOAD2f -1000.0 -1000.0 1000.0 1000.0
2MAHMP 0.0 0.0 1000.0 1000.0
3OAS180 0.0 0.0 1000.0 1000.0
34dhpactex -1000.0 -1000.0 1000.0 1000.0
3AMPtex -1000.0 -1000.0 1000.0 1000.0
ACOAD3f -1000.0 -1000.0 1000.0 1000.0
ACOAD4f -1000.0 -1000.0 1000.0 1000.0
ACOAD5f -1000.0 -1000.0 1000.0 1000.0
3CMPtex -1000.0 -1000.0 1000.0 1000.0
3OAS181 0.0 0.0 1000.0 1000.0
3GMPtex -1000.0 -1000.0 1000.0 1000.0
3HAD100 0.0 0.0 1000.0 1000.0
3HAD120 0.0 0.0 1000.0 1000.0
ACOAD6f -1000.0 -1000.0 1000.0 1000.0
ACOAD7f -1000.0 -1000.0 1000.0 1000.0
ACOAD8f -1000.0 -1000.0 1000.0 1000.0
ACOATA -1000.0 -1000.0 1000.0 1000.0
3HAD121 0.0 0.0 1000.0 1000.0
ACODA 0.0 0.0 1000.0 1000.0
3OAS60 0.0 0.0 1000.0 1000.0
3HAD140 0.0 0.0 1000.0 1000.0
3OAS80 0.0 0.0 1000.0 1000.0
3HAD141 0.0 0.0 1000.0 1000.0
3PEPTabcpp 0.0 0.0 1000.0 1000.0
3HAD160 0.0 0.0 1000.0 1000.0
3HAD161 0.0 0.0 1000.0 1000.0
ACOLIPAtex 0.0 0.0 1000.0 1000.0
ACONIs -1000.0 -1000.0 1000.0 1000.0
ACONTa -1000.0 -1000.0 1000.0 1000.0
ACONTb -1000.0 -1000.0 1000.0 1000.0
ADK1 0.0 0.0 1000.0 1000.0
ADK3 -1000.0 -1000.0 1000.0 1000.0
ACOTA -1000.0 -1000.0 1000.0 1000.0
3PEPTtex -1000.0 -1000.0 1000.0 1000.0
ACPS1 0.0 0.0 1000.0 1000.0
ACS 0.0 0.0 1000.0 1000.0
ACSERtex -1000.0 -1000.0 1000.0 1000.0
ADK4 -1000.0 -1000.0 1000.0 1000.0
ADMDC 0.0 0.0 1000.0 1000.0
ADNCYC 0.0 0.0 1000.0 1000.0
3UMPtex -1000.0 -1000.0 1000.0 1000.0
ADNK1 0.0 0.0 1000.0 1000.0
ADNUC 0.0 0.0 1000.0 1000.0
ADNt2pp_copy1 0.0 0.0 1000.0 1000.0
ACSERtpp 0.0 0.0 1000.0 1000.0
ACt2rpp -1000.0 -1000.0 1000.0 1000.0
ACt4pp 0.0 0.0 1000.0 1000.0
ADNt2pp_copy2 -1000.0 -1000.0 1000.0 1000.0
4HOXPACDtex -1000.0 -1000.0 1000.0 1000.0
ADNtex -1000.0 -1000.0 1000.0 1000.0
ADOCBLabcpp 0.0 0.0 1000.0 1000.0
ACtex -1000.0 -1000.0 1000.0 1000.0
ADA 0.0 0.0 1000.0 1000.0
ADCL 0.0 0.0 1000.0 1000.0
ADOCBLtonex 0.0 0.0 1000.0 1000.0
ADPRDP 0.0 0.0 1000.0 1000.0
ADCS 0.0 0.0 1000.0 1000.0
ADEt2rpp -1000.0 -1000.0 1000.0 1000.0
ADEtex -1000.0 -1000.0 1000.0 1000.0
ADPT 0.0 0.0 1000.0 1000.0
ADSK 0.0 0.0 1000.0 1000.0
ADSL1r -1000.0 -1000.0 1000.0 1000.0
4PCP 0.0 0.0 1000.0 1000.0
ADSL2r -1000.0 -1000.0 1000.0 1000.0
ADSS 0.0 0.0 1000.0 1000.0
AGDC 0.0 0.0 1000.0 1000.0
ALDD3y 0.0 0.0 1000.0 1000.0
ALLTAMH 0.0 0.0 1000.0 1000.0
AGM3PA 0.0 0.0 1000.0 1000.0
4PCPpp 0.0 0.0 1000.0 1000.0
AGM3PApp 0.0 0.0 1000.0 1000.0
AGM3PH 0.0 0.0 1000.0 1000.0
ALLTN 0.0 0.0 1000.0 1000.0
ALLTNt2rpp -1000.0 -1000.0 1000.0 1000.0
AGM3Pt2pp 0.0 0.0 1000.0 1000.0
ALLTNtex -1000.0 -1000.0 1000.0 1000.0
AGM4PA 0.0 0.0 1000.0 1000.0
4PEPTabcpp 0.0 0.0 1000.0 1000.0
AGM4PApp 0.0 0.0 1000.0 1000.0
ALLtex -1000.0 -1000.0 1000.0 1000.0
4PEPTtex -1000.0 -1000.0 1000.0 1000.0
ALR2 0.0 0.0 1000.0 1000.0
ALR4x 0.0 0.0 1000.0 1000.0
AGM4PCP 0.0 0.0 1000.0 1000.0
AGM4PCPpp 0.0 0.0 1000.0 1000.0
AM3PA 0.0 0.0 1000.0 1000.0
AM4PA 0.0 0.0 1000.0 1000.0
5DGLCNR -1000.0 -1000.0 1000.0 1000.0
AM4PCP 0.0 0.0 1000.0 1000.0
AMALT1 0.0 0.0 1000.0 1000.0
AMALT2 0.0 0.0 1000.0 1000.0
AMALT3 0.0 0.0 1000.0 1000.0
AMALT4 0.0 0.0 1000.0 1000.0
AGM4PH 0.0 0.0 1000.0 1000.0
AGM4Pt2pp 0.0 0.0 1000.0 1000.0
AGMH 0.0 0.0 1000.0 1000.0
AGMHE 0.0 0.0 1000.0 1000.0
AGMT 0.0 0.0 1000.0 1000.0
AGMt2pp 0.0 0.0 1000.0 1000.0
AMANAPEr -1000.0 -1000.0 1000.0 1000.0
AMANK 0.0 0.0 1000.0 1000.0
AMAOTr -1000.0 -1000.0 1000.0 1000.0
AGMtex -1000.0 -1000.0 1000.0 1000.0
5DGLCNt2rpp -1000.0 -1000.0 1000.0 1000.0
AGPAT120 0.0 0.0 1000.0 1000.0
AGPAT140 0.0 0.0 1000.0 1000.0
AMMQLT8 0.0 0.0 1000.0 1000.0
AMPMS2 0.0 0.0 1000.0 1000.0
5DGLCNtex -1000.0 -1000.0 1000.0 1000.0
AMPN 0.0 0.0 1000.0 1000.0
AMPTASECG 0.0 0.0 1000.0 1000.0
AMPTASEPG 0.0 0.0 1000.0 1000.0
AGPAT141 0.0 0.0 1000.0 1000.0
AGPAT160 0.0 0.0 1000.0 1000.0
AGPAT161 0.0 0.0 1000.0 1000.0
AMPtex -1000.0 -1000.0 1000.0 1000.0
5DOAN 0.0 0.0 1000.0 1000.0
ANHGMtex -1000.0 -1000.0 1000.0 1000.0
ANHMK 0.0 0.0 1000.0 1000.0
AGPAT180 0.0 0.0 1000.0 1000.0
AGPAT181 0.0 0.0 1000.0 1000.0
AGPR -1000.0 -1000.0 1000.0 1000.0
AHCYSNS 0.0 0.0 1000.0 1000.0
ANPRT 0.0 0.0 1000.0 1000.0
ANS 0.0 0.0 1000.0 1000.0
AOBUTDs 0.0 0.0 1000.0 1000.0
AOXSr -1000.0 -1000.0 1000.0 1000.0
AP4AH 0.0 0.0 1000.0 1000.0
AICART -1000.0 -1000.0 1000.0 1000.0
AIRC2 0.0 0.0 1000.0 1000.0
AP5AH 0.0 0.0 1000.0 1000.0
A5PISO -1000.0 -1000.0 1000.0 1000.0
APRAUR 0.0 0.0 1000.0 1000.0
AIRC3 -1000.0 -1000.0 1000.0 1000.0
AKGDH 0.0 0.0 1000.0 1000.0
ARAI -1000.0 -1000.0 1000.0 1000.0
AACPS1 0.0 0.0 1000.0 1000.0
ARBTNR1 0.0 0.0 1000.0 1000.0
ARBTNR2 0.0 0.0 1000.0 1000.0
AKGt2rpp -1000.0 -1000.0 1000.0 1000.0
AKGtex -1000.0 -1000.0 1000.0 1000.0
ARBTNR3 0.0 0.0 1000.0 1000.0
ALAALAabcpp 0.0 0.0 1000.0 1000.0
AACPS2 0.0 0.0 1000.0 1000.0
ALAALAr 0.0 0.0 1000.0 1000.0
ALAALAtex -1000.0 -1000.0 1000.0 1000.0
ARBTNabcpp 0.0 0.0 1000.0 1000.0
ARBTNexs 0.0 0.0 1000.0 1000.0
ARBTNtex 0.0 0.0 1000.0 1000.0
ALAGLUE -1000.0 -1000.0 1000.0 1000.0
ALAR -1000.0 -1000.0 1000.0 1000.0
ALATA_D2 0.0 0.0 1000.0 1000.0
AACPS3 0.0 0.0 1000.0 1000.0
ALATA_L -1000.0 -1000.0 1000.0 1000.0
ALATA_L2 0.0 0.0 1000.0 1000.0
ALATRS 0.0 0.0 1000.0 1000.0
ALAabcpp 0.0 0.0 1000.0 1000.0
ARBTNtonex 0.0 0.0 1000.0 1000.0
ARBTNtpp 0.0 0.0 1000.0 1000.0
ARBt2rpp -1000.0 -1000.0 1000.0 1000.0
ARBt3ipp 0.0 0.0 1000.0 1000.0
ARBtex -1000.0 -1000.0 1000.0 1000.0
ARGAGMt7pp -1000.0 -1000.0 1000.0 1000.0
ALAt2pp 0.0 0.0 1000.0 1000.0
ALAt4pp 0.0 0.0 1000.0 1000.0
ARGDC 0.0 0.0 1000.0 1000.0
AACPS4 0.0 0.0 1000.0 1000.0
ARGDCpp 0.0 0.0 1000.0 1000.0
ARGORNt7pp -1000.0 -1000.0 1000.0 1000.0
ALAtex -1000.0 -1000.0 1000.0 1000.0
ALDD2y 0.0 0.0 1000.0 1000.0
ARGSL -1000.0 -1000.0 1000.0 1000.0
AACPS5 0.0 0.0 1000.0 1000.0
ARGSS 0.0 0.0 1000.0 1000.0
ARGTRS 0.0 0.0 1000.0 1000.0
ASNNpp 0.0 0.0 1000.0 1000.0
AACPS6 0.0 0.0 1000.0 1000.0
ASNS1 0.0 0.0 1000.0 1000.0
ARGabcpp 0.0 0.0 1000.0 1000.0
ARGt3pp 0.0 0.0 1000.0 1000.0
ASNS2 0.0 0.0 1000.0 1000.0
AACPS7 0.0 0.0 1000.0 1000.0
ARGtex -1000.0 -1000.0 1000.0 1000.0
ASAD -1000.0 -1000.0 1000.0 1000.0
AACPS8 0.0 0.0 1000.0 1000.0
ASCBPL 0.0 0.0 1000.0 1000.0
ASCBptspp 0.0 0.0 1000.0 1000.0
ASCBtex -1000.0 -1000.0 1000.0 1000.0
AACPS9 0.0 0.0 1000.0 1000.0
ASNN 0.0 0.0 1000.0 1000.0
AACTOOR 0.0 0.0 1000.0 1000.0
AAMYL 0.0 0.0 1000.0 1000.0
ASNTRS_1 0.0 0.0 1000.0 1000.0
AAMYLpp 0.0 0.0 1000.0 1000.0
ASNabcpp 0.0 0.0 1000.0 1000.0
ABTA 0.0 0.0 1000.0 1000.0
ASNt2rpp -1000.0 -1000.0 1000.0 1000.0
ABUTD 0.0 0.0 1000.0 1000.0
ASNtex -1000.0 -1000.0 1000.0 1000.0
ASO3tex -1000.0 -1000.0 1000.0 1000.0
ABUTt2pp 0.0 0.0 1000.0 1000.0
ASP1DC 0.0 0.0 1000.0 1000.0
CRNDCAL2 0.0 0.0 1000.0 1000.0
ASPCT 0.0 0.0 1000.0 1000.0
ASPK -1000.0 -1000.0 1000.0 1000.0
ASPO3 0.0 0.0 1000.0 1000.0
ASPO4 0.0 0.0 1000.0 1000.0
ASPO5 0.0 0.0 1000.0 1000.0
ASPO6 0.0 0.0 1000.0 1000.0
CDPMEK 0.0 0.0 1000.0 1000.0
CFAS160E 0.0 0.0 1000.0 1000.0
CFAS160G 0.0 0.0 1000.0 1000.0
CFAS180E 0.0 0.0 1000.0 1000.0
CRNDabcpp 0.0 0.0 1000.0 1000.0
CFAS180G 0.0 0.0 1000.0 1000.0
CGLYabcpp 0.0 0.0 1000.0 1000.0
ASPT 0.0 0.0 1000.0 1000.0
ASPTA -1000.0 -1000.0 1000.0 1000.0
CGLYtex -1000.0 -1000.0 1000.0 1000.0
CHLabcpp 0.0 0.0 1000.0 1000.0
CHLtex -1000.0 -1000.0 1000.0 1000.0
ASPTRS 0.0 0.0 1000.0 1000.0
ASPabcpp 0.0 0.0 1000.0 1000.0
ASPt2_2pp 0.0 0.0 1000.0 1000.0
ASPt2pp 0.0 0.0 1000.0 1000.0
CHORS 0.0 0.0 1000.0 1000.0
CHRPL 0.0 0.0 1000.0 1000.0
ASPtex -1000.0 -1000.0 1000.0 1000.0
AST 0.0 0.0 1000.0 1000.0
CITL 0.0 0.0 1000.0 1000.0
CRNDt2rpp -1000.0 -1000.0 1000.0 1000.0
CITt7pp 0.0 0.0 1000.0 1000.0
CITtex -1000.0 -1000.0 1000.0 1000.0
ATHRDHr -1000.0 -1000.0 1000.0 1000.0
ATPHs 0.0 0.0 1000.0 1000.0
ATPM 8.39 8.39 8.39 8.39
CRNabcpp 0.0 0.0 1000.0 1000.0
ATPPRT 0.0 0.0 1000.0 1000.0
CRNt2rpp -1000.0 -1000.0 1000.0 1000.0
ATPS4rpp -1000.0 -1000.0 1000.0 1000.0
ICITtex -1000.0 -1000.0 1000.0 1000.0
CRNt7pp 0.0 0.0 1000.0 1000.0
ACONCtex -1000.0 -1000.0 1000.0 1000.0
BALAt2pp 0.0 0.0 1000.0 1000.0
BALAtex -1000.0 -1000.0 1000.0 1000.0
CRNt8pp 0.0 0.0 1000.0 1000.0
BPNT 0.0 0.0 1000.0 1000.0
BSORx 0.0 0.0 1000.0 1000.0
BSORy 0.0 0.0 1000.0 1000.0
BTS4 0.0 0.0 1000.0 1000.0
BUTSO3tex -1000.0 -1000.0 1000.0 1000.0
CLIPAtex 0.0 0.0 1000.0 1000.0
CLPNH120pp 0.0 0.0 1000.0 1000.0
CLPNH140pp 0.0 0.0 1000.0 1000.0
CLPNH141pp 0.0 0.0 1000.0 1000.0
CLPNH160pp 0.0 0.0 1000.0 1000.0
CLPNH161pp 0.0 0.0 1000.0 1000.0
CLPNH180pp 0.0 0.0 1000.0 1000.0
BUTtex -1000.0 -1000.0 1000.0 1000.0
CLPNH181pp 0.0 0.0 1000.0 1000.0
CRNtex -1000.0 -1000.0 1000.0 1000.0
CLPNS120pp -1000.0 -1000.0 1000.0 1000.0
CA2t3pp 0.0 0.0 1000.0 1000.0
CS 0.0 0.0 1000.0 1000.0
CA2tex -1000.0 -1000.0 1000.0 1000.0
CADVtpp 0.0 0.0 1000.0 1000.0
CLPNS140pp -1000.0 -1000.0 1000.0 1000.0
CLPNS141pp -1000.0 -1000.0 1000.0 1000.0
CAt6pp -1000.0 -1000.0 1000.0 1000.0
CLPNS160pp -1000.0 -1000.0 1000.0 1000.0
CSNtex -1000.0 -1000.0 1000.0 1000.0
CLPNS161pp -1000.0 -1000.0 1000.0 1000.0
CLPNS180pp -1000.0 -1000.0 1000.0 1000.0
CBIAT -1000.0 -1000.0 1000.0 1000.0
CBItonex 0.0 0.0 1000.0 1000.0
CBIuabcpp 0.0 0.0 1000.0 1000.0
CBL1abcpp 0.0 0.0 1000.0 1000.0
CLPNS181pp -1000.0 -1000.0 1000.0 1000.0
CTBTCAL2 0.0 0.0 1000.0 1000.0
CLt3_2pp 0.0 0.0 1000.0 1000.0
CLtex -1000.0 -1000.0 1000.0 1000.0
CMPN 0.0 0.0 1000.0 1000.0
CMPtex -1000.0 -1000.0 1000.0 1000.0
CBL1tonex 0.0 0.0 1000.0 1000.0
CBPS 0.0 0.0 1000.0 1000.0
CD2abcpp 0.0 0.0 1000.0 1000.0
CD2t3pp 0.0 0.0 1000.0 1000.0
CD2tex -1000.0 -1000.0 1000.0 1000.0
CD2tpp 0.0 0.0 1000.0 1000.0
CDAPPA120 0.0 0.0 1000.0 1000.0
CO2tex -1000.0 -1000.0 1000.0 1000.0
CO2tpp -1000.0 -1000.0 1000.0 1000.0
CDAPPA140 0.0 0.0 1000.0 1000.0
CTBTabcpp 0.0 0.0 1000.0 1000.0
CDAPPA141 0.0 0.0 1000.0 1000.0
CDAPPA160 0.0 0.0 1000.0 1000.0
COBALT2abcpp 0.0 0.0 1000.0 1000.0
COBALT2t3pp 0.0 0.0 1000.0 1000.0
COBALT2tex -1000.0 -1000.0 1000.0 1000.0
CTBTt2rpp -1000.0 -1000.0 1000.0 1000.0
COBALT2tpp_copy1 0.0 0.0 1000.0 1000.0
COLIPAabcpp 0.0 0.0 1000.0 1000.0
COLIPAtex 0.0 0.0 1000.0 1000.0
CDAPPA161 0.0 0.0 1000.0 1000.0
CDAPPA180 0.0 0.0 1000.0 1000.0
CDAPPA181 0.0 0.0 1000.0 1000.0
CPGNR1 0.0 0.0 1000.0 1000.0
CTPS2 0.0 0.0 1000.0 1000.0
CPGNR2 0.0 0.0 1000.0 1000.0
CPGNR3 0.0 0.0 1000.0 1000.0
CU1Opp 0.0 0.0 1000.0 1000.0
CPGNUtex 0.0 0.0 1000.0 1000.0
CPGNUtpp 0.0 0.0 1000.0 1000.0
CPGNabcpp 0.0 0.0 1000.0 1000.0
CPGNexs 0.0 0.0 1000.0 1000.0
DAMPtex -1000.0 -1000.0 1000.0 1000.0
DAPDC 0.0 0.0 1000.0 1000.0
DAPE -1000.0 -1000.0 1000.0 1000.0
DAPabcpp 0.0 0.0 1000.0 1000.0
DAPtex -1000.0 -1000.0 1000.0 1000.0
CPGNtonex 0.0 0.0 1000.0 1000.0
CU1abcpp 0.0 0.0 1000.0 1000.0
CPPPGO 0.0 0.0 1000.0 1000.0
CPPPGO2 0.0 0.0 1000.0 1000.0
DASYN120 0.0 0.0 1000.0 1000.0
DASYN140 0.0 0.0 1000.0 1000.0
CRNBTCT -1000.0 -1000.0 1000.0 1000.0
AU1abcpp 0.0 0.0 1000.0 1000.0
CRNCAL2 0.0 0.0 1000.0 1000.0
CRNCAR -1000.0 -1000.0 1000.0 1000.0
CRNCBCT -1000.0 -1000.0 1000.0 1000.0
DASYN141 0.0 0.0 1000.0 1000.0
DASYN160 0.0 0.0 1000.0 1000.0
DASYN161 0.0 0.0 1000.0 1000.0
DASYN180 0.0 0.0 1000.0 1000.0
CRNCDH -1000.0 -1000.0 1000.0 1000.0
CU2abcpp 0.0 0.0 1000.0 1000.0
DASYN181 0.0 0.0 1000.0 1000.0
DATPHs 0.0 0.0 1000.0 1000.0
CU2tex -1000.0 -1000.0 1000.0 1000.0
DB4PS 0.0 0.0 1000.0 1000.0
DBTS 0.0 0.0 1000.0 1000.0
DMQMT 0.0 0.0 1000.0 1000.0
CU2tpp 0.0 0.0 1000.0 1000.0
DMSOtex -1000.0 -1000.0 1000.0 1000.0
DMStex -1000.0 -1000.0 1000.0 1000.0
DM_4hba_c 0.0 0.0 1000.0 1000.0
DCAtex -1000.0 -1000.0 1000.0 1000.0
DCMPtex -1000.0 -1000.0 1000.0 1000.0
DCTPD 0.0 0.0 1000.0 1000.0
DCYTD 0.0 0.0 1000.0 1000.0
DCYTt2pp 0.0 0.0 1000.0 1000.0
CUtex -1000.0 -1000.0 1000.0 1000.0
DCYTtex -1000.0 -1000.0 1000.0 1000.0
DDCAtexi 0.0 0.0 1000.0 1000.0
DDGALK 0.0 0.0 1000.0 1000.0
DM_5drib_c 0.0 0.0 1000.0 1000.0
DM_hmfurn_c 0.0 0.0 1000.0 1000.0
DM_oxam_c 0.0 0.0 1000.0 1000.0
DNMPPA 0.0 0.0 1000.0 1000.0
DNTPPA 0.0 0.0 1000.0 1000.0
DDGLCNtex -1000.0 -1000.0 1000.0 1000.0
CYANST 0.0 0.0 1000.0 1000.0
DDGLK 0.0 0.0 1000.0 1000.0
DDPA 0.0 0.0 1000.0 1000.0
DGK1 -1000.0 -1000.0 1000.0 1000.0
DOGULNR 0.0 0.0 1000.0 1000.0
DOPAtex -1000.0 -1000.0 1000.0 1000.0
DPCOAK 0.0 0.0 1000.0 1000.0
DRPA 0.0 0.0 1000.0 1000.0
DGMPtex -1000.0 -1000.0 1000.0 1000.0
DGSNt2pp 0.0 0.0 1000.0 1000.0
CYANSTpp 0.0 0.0 1000.0 1000.0
DGSNtex -1000.0 -1000.0 1000.0 1000.0
DSBAO1 0.0 0.0 1000.0 1000.0
DSBAO2 0.0 0.0 1000.0 1000.0
DSBCGT 0.0 0.0 1000.0 1000.0
DSBDR 0.0 0.0 1000.0 1000.0
DSBGGT 0.0 0.0 1000.0 1000.0
DHAD1 0.0 0.0 1000.0 1000.0
DHAD2 0.0 0.0 1000.0 1000.0
DHAtex -1000.0 -1000.0 1000.0 1000.0
DHAtpp -1000.0 -1000.0 1000.0 1000.0
DHBD 0.0 0.0 1000.0 1000.0
DSERDHr -1000.0 -1000.0 1000.0 1000.0
DSERt2pp 0.0 0.0 1000.0 1000.0
DSERtex -1000.0 -1000.0 1000.0 1000.0
DHBS 0.0 0.0 1000.0 1000.0
CYANtex -1000.0 -1000.0 1000.0 1000.0
DHDPRy 0.0 0.0 1000.0 1000.0
DHDPS 0.0 0.0 1000.0 1000.0
DTMPK -1000.0 -1000.0 1000.0 1000.0
DTMPtex -1000.0 -1000.0 1000.0 1000.0
CYNTtex -1000.0 -1000.0 1000.0 1000.0
DUMPtex -1000.0 -1000.0 1000.0 1000.0
DURIK1 0.0 0.0 1000.0 1000.0
DURIPP -1000.0 -1000.0 1000.0 1000.0
DHFR -1000.0 -1000.0 1000.0 1000.0
DHFS 0.0 0.0 1000.0 1000.0
DHNAOT4 0.0 0.0 1000.0 1000.0
DURIt2pp 0.0 0.0 1000.0 1000.0
DURItex -1000.0 -1000.0 1000.0 1000.0
DHNPA2r 0.0 0.0 1000.0 1000.0
DUTPDP 0.0 0.0 1000.0 1000.0
DHORD2 0.0 0.0 1000.0 1000.0
CYSDS_copy1 0.0 0.0 1000.0 1000.0
DHORD5 0.0 0.0 1000.0 1000.0
DHORTS -1000.0 -1000.0 1000.0 1000.0
DXPRIi 0.0 0.0 1000.0 1000.0
DXPS 0.0 0.0 1000.0 1000.0
DXYLK 0.0 0.0 1000.0 1000.0
DHPPDA2 0.0 0.0 1000.0 1000.0
DHPS2 0.0 0.0 1000.0 1000.0
CYSDtex -1000.0 -1000.0 1000.0 1000.0
DHPTDCs 0.0 0.0 1000.0 1000.0
D_LACt2pp -1000.0 -1000.0 1000.0 1000.0
D_LACtex -1000.0 -1000.0 1000.0 1000.0
DHQS 0.0 0.0 1000.0 1000.0
DHQTi 0.0 0.0 1000.0 1000.0
E4PD 0.0 0.0 1000.0 1000.0
CYSS 0.0 0.0 1000.0 1000.0
EAR100x 0.0 0.0 1000.0 1000.0
EAR100y 0.0 0.0 1000.0 1000.0
DIMPtex -1000.0 -1000.0 1000.0 1000.0
DINSt2pp 0.0 0.0 1000.0 1000.0
EAR120x 0.0 0.0 1000.0 1000.0
DINStex -1000.0 -1000.0 1000.0 1000.0
EAR120y 0.0 0.0 1000.0 1000.0
CYSSADS 0.0 0.0 1000.0 1000.0
EAR121x 0.0 0.0 1000.0 1000.0
EAR121y 0.0 0.0 1000.0 1000.0
DKGLCNR1 0.0 0.0 1000.0 1000.0
DKGLCNR2x 0.0 0.0 1000.0 1000.0
EAR140x 0.0 0.0 1000.0 1000.0
DKGLCNR2y 0.0 0.0 1000.0 1000.0
CYSTL 0.0 0.0 1000.0 1000.0
DKMPPD 0.0 0.0 1000.0 1000.0
EAR140y 0.0 0.0 1000.0 1000.0
EAR141x 0.0 0.0 1000.0 1000.0
DKMPPD3 0.0 0.0 1000.0 1000.0
DMATT 0.0 0.0 1000.0 1000.0
DMPPS 0.0 0.0 1000.0 1000.0
EAR141y 0.0 0.0 1000.0 1000.0
EAR160x 0.0 0.0 1000.0 1000.0
EAR160y 0.0 0.0 1000.0 1000.0
EAR161x 0.0 0.0 1000.0 1000.0
CYSTRS 0.0 0.0 1000.0 1000.0
EAR161y 0.0 0.0 1000.0 1000.0
EAR180x 0.0 0.0 1000.0 1000.0
EAR180y 0.0 0.0 1000.0 1000.0
EAR181x 0.0 0.0 1000.0 1000.0
EX_alaala_e 0.0 0.0 1000.0 1000.0
EAR181y 0.0 0.0 1000.0 1000.0
ECAP3pp 0.0 0.0 1000.0 1000.0
CYSabc2pp 0.0 0.0 1000.0 1000.0
ECAtpp 0.0 0.0 1000.0 1000.0
ECOAH1 -1000.0 -1000.0 1000.0 1000.0
EAR40x 0.0 0.0 1000.0 1000.0
EAR40y 0.0 0.0 1000.0 1000.0
EAR60x 0.0 0.0 1000.0 1000.0
EAR60y 0.0 0.0 1000.0 1000.0
ECOAH2 -1000.0 -1000.0 1000.0 1000.0
CYSabcpp 0.0 0.0 1000.0 1000.0
ECOAH3 -1000.0 -1000.0 1000.0 1000.0
ECOAH4 -1000.0 -1000.0 1000.0 1000.0
EAR80x 0.0 0.0 1000.0 1000.0
EAR80y 0.0 0.0 1000.0 1000.0
ECA4COLIPAtex 0.0 0.0 1000.0 1000.0
ECOAH5 -1000.0 -1000.0 1000.0 1000.0
CYSIabcpp 0.0 0.0 1000.0 1000.0
ECOAH6 -1000.0 -1000.0 1000.0 1000.0
ECA4OALpp 0.0 0.0 1000.0 1000.0
ECAP1pp 0.0 0.0 1000.0 1000.0
ECAP2pp 0.0 0.0 1000.0 1000.0
ECOAH7 -1000.0 -1000.0 1000.0 1000.0
ECOAH8 -1000.0 -1000.0 1000.0 1000.0
EDA 0.0 0.0 1000.0 1000.0
CYStex -1000.0 -1000.0 1000.0 1000.0
EDD 0.0 0.0 1000.0 1000.0
EDTXS1 0.0 0.0 1000.0 1000.0
CYSItex -1000.0 -1000.0 1000.0 1000.0
EDTXS2 0.0 0.0 1000.0 1000.0
EDTXS3 0.0 0.0 1000.0 1000.0
CYStpp 0.0 0.0 1000.0 1000.0
EDTXS4 0.0 0.0 1000.0 1000.0
ENLIPAtex 0.0 0.0 1000.0 1000.0
CYTBO3_4pp 0.0 0.0 1000.0 1000.0
EX_all__D_e 0.0 0.0 1000.0 1000.0
ENO -1000.0 -1000.0 1000.0 1000.0
CYTD 0.0 0.0 1000.0 1000.0
CYTDH 0.0 0.0 1000.0 1000.0
CYTDK2 0.0 0.0 1000.0 1000.0

# check simulation results

## FBA Overall Growth Rate for all models

In [32]:
fba_stm1090 = stm1090_model.optimize()
fba_stm1585 = stm1585_model.optimize()
fba_stm2575 = stm2575_model.optimize()
fba_base = base_model.optimize()

In [33]:
stm1090_model.summary()

In [34]:
print(fba_base.objective_value)
print(fba_stm1090.objective_value)
print(fba_stm1585.objective_value)
print(fba_stm2575.objective_value)

0.4778336607607207
0.40720580512198207
0.40650099210576757
0.39342197276970997

# Making sense of the predicted growth rates

What is growth rate in FBA? 

What does the number mean biologically? 

What growth rate values should we expect? 

How can we compare between values?
Let's use the predicted growth rate of the input model as a control to gauge how different the predictions are for the extracted models. I'll divide the growth rate of the input model by the growth rate of each extracted model to see the percent change.

# Calculating percent decrease and percent retained

In [35]:
# (1) calculate the difference in growth prediction. base model - extracted model = difference
# (2) divide the difference by the base model
# (3) convert the result of each division to a percentage (multiply by 100)

# Coding work
Inspect the variables I'm using first. 
```
type(fba_base.objective_value) = float
dir(fba_base.objective_value)
print(fba_base.objective_value) = 0.4778336607607207
```
From this I know that my objective values are float (numbers with a decimal point) and I know that when I print it out, I get a long decimal. 

I want to (1) have a math equation that solves the difference of extracted model and the base model and (2) takes the difference and calculates what percentage it is of the base model. The final answer should be to the second decimal point.

In [36]:
# calculate percent difference for each extracted model 
# percent_decrease = ((input_model - extracted_model) / input_model) * 100

stm1090_decrease = ((fba_base.objective_value - fba_stm1090.objective_value) / (fba_base.objective_value))
print(stm1090_decrease)

# The value assigned to the variable `stm1090_decrease` is a float. 
# I need to multiply by 100, convert to a percent, and round to the second decimal point. 

#  `format()` is a built in python function that converts the value to a string-representation of a specified format. 
# in this case, I am turning a decimal number into a percentage string with two digits after the decimal
# `format(float, ".2%") - `float` is the number that I want to change. "%" is saying take this decimal number, multiply it by 100,
# and add a percent sign. The `.2` is saying round to the second decimal point. 

stm1090_percentdecrease = format(stm1090_decrease, ".2%")
print(stm1090_percentdecrease)

stm1585_decrease = ((fba_base.objective_value - fba_stm1585.objective_value) / (fba_base.objective_value))
print(stm1585_decrease)
stm1585_percentdecrease = format(stm1585_decrease, ".2%")
print(stm1585_percentdecrease)

stm2575_decrease = ((fba_base.objective_value - fba_stm2575.objective_value) / (fba_base.objective_value))
print(stm2575_decrease)
stm2575_percentdecrease = format(stm2575_decrease, ".2%")
print(stm2575_percentdecrease)

0.1478084560353025
14.78%
0.14928347354472707
14.93%
0.17665496368888212
17.67%

In [37]:
# I can also calculate the percent of growth retained from the input model
# percent retained = (extracted_model / input_model) * 100

stm1090_percentretained = fba_stm1090.objective_value / fba_base.objective_value
print(format(stm1090_percentretained, ".2%"))

stm1585_percentretained = fba_stm1585.objective_value / fba_base.objective_value
print(format(stm1585_percentretained, ".2%"))

stm2575_percentretained = fba_stm2575.objective_value / fba_base.objective_value
print(format(stm2575_percentretained, ".2%"))

85.22%
85.07%
82.33%

Models `stm1090_model` and `stm1585_model` have predicted growth rates that are almost the same. They have a predicted growth rate of 14.78% and 14.93% lower than the input model's growth rate, respecitively. This suggests that threshold categories of 10%/90% and 15%/85% do not make a noticeable impact on overall growth rate predictions given these constraints. It is possible that the predicted growth rate could noticeably change once the environmental conditions are altered.

In [38]:
print(f"{stm1090_percent_decrease:.2f}%")

NameError: name 'stm1090_percent_decrease' is not defined