# Comparing across the Extracted, Context-Specific Salmonella GEMs and Exploring Experimental Applications

**Author:** Gina Vazquez  
**Date:** March 30 2026 - 

## Goal
- Quantify the amount of reactions across the models. 
- Systematically delete each gene in a model and use FBA to test the model for normal or impaired growth.
- Functionality score

## Dataset

## Notes

## Workflow
1.

In [1]:
import pandas
from time import time

import cobra

from cobra.io import from_json, load_json_model
from cobra.flux_analysis import single_gene_deletion
from cobra.flux_analysis import flux_variability_analysis

In [2]:
import os

os.environ["GRB_LICENSE_FILE"] = "/home/gmvaz/.gurobi.lic"
#export GRB_LICENSE_FILE=$HOME/.gurobi.lic

Load a subset of the extracted models.

In [3]:
mixed1090_eliminate = load_json_model("run_031526/context_models/mixed1090_eliminate.json")
mixed1090_imat_restrictions = load_json_model("run_031526/context_models/mixed1090_imat_restrictions.json")
mixed1090_MILP = load_json_model("run_031526/context_models/mixed1090_MILP.json")
mixed1090_simple_bounds = load_json_model("run_031526/context_models/mixed1090_simple_bounds.json")

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2789960
Academic license 2789960 - for non-commercial use only - registered to gm___@ucdavis.edu

Load the base Salmonella Tm. model.

In [18]:
stm_v1 = load_json_model("STM_v1_0.json")
stmv1fba = stm_v1.optimize()

In [20]:
print(stmv1fba)
stm_v1.summary()

<Solution 0.478 at 0x7e95735bb1d0>

Compare the amount of reactions, metabolites, and genes in an extracted model and the base model.

In [5]:
print(len(mixed1090_imat_restrictions.reactions))
print(len(mixed1090_imat_restrictions.metabolites))
print(len(mixed1090_imat_restrictions.genes))

print(len(stm_v1.reactions))
print(len(stm_v1.metabolites))
print(len(stm_v1.genes))

2545
1802
1271
2545
1802
1271

Optimize the extracted model using flux balance analysis.

In [6]:
mixed1090_imat_restrictions_FBA = mixed1090_imat_restrictions.optimize()
print(mixed1090_imat_restrictions_FBA)

<Solution 0.478 at 0x7e9584860e50>

Get the optimal value for the objective function.

In [14]:
mixed1090_imat_restrictions.summary()

In [17]:
nofba = mixed1090_eliminate.summary()
print(nofba)
mixed1090_eliminate.optimize()
withfba = mixed1090_eliminate.summary()
print(withfba)

Objective
=========
1.0 BIOMASS_iRR1083_metals = 0.477833660760721

Uptake
------
Metabolite     Reaction     Flux  C-Number  C-Flux
     ca2_e     EX_ca2_e 0.002263         0   0.00%
      cl_e      EX_cl_e 0.002263         0   0.00%
 cobalt2_e EX_cobalt2_e 0.001509         0   0.00%
     cu2_e     EX_cu2_e 0.001509         0   0.00%
     fe2_e     EX_fe2_e 0.003502         0   0.00%
  glc__D_e  EX_glc__D_e        5         6 100.00%
       k_e       EX_k_e  0.08486         0   0.00%
     mg2_e     EX_mg2_e 0.003772         0   0.00%
     mn2_e     EX_mn2_e 0.001509         0   0.00%
    mobd_e    EX_mobd_e 0.001509         0   0.00%
     nh4_e     EX_nh4_e    5.266         0   0.00%
      o2_e      EX_o2_e    11.65         0   0.00%
      pi_e      EX_pi_e   0.4238         0   0.00%
     so4_e     EX_so4_e  0.05829         0   0.00%
     zn2_e     EX_zn2_e 0.001509         0   0.00%

Secretion
---------
Metabolite    Reaction       Flux  C-Number C-Flux
  hmfurn_c DM_hmfurn_c -0.0002131         5  0.01%
     co2_e    EX_co2_e     -11.52         1 99.99%
     h2o_e    EX_h2o_e     -24.69         0  0.00%
       h_e      EX_h_e     -4.051         0  0.00%

Objective
=========
1.0 BIOMASS_iRR1083_metals = 0.477833660760721

Uptake
------
Metabolite     Reaction     Flux  C-Number  C-Flux
     ca2_e     EX_ca2_e 0.002263         0   0.00%
      cl_e      EX_cl_e 0.002263         0   0.00%
 cobalt2_e EX_cobalt2_e 0.001509         0   0.00%
     cu2_e     EX_cu2_e 0.001509         0   0.00%
     fe2_e     EX_fe2_e 0.003502         0   0.00%
  glc__D_e  EX_glc__D_e        5         6 100.00%
       k_e       EX_k_e  0.08486         0   0.00%
     mg2_e     EX_mg2_e 0.003772         0   0.00%
     mn2_e     EX_mn2_e 0.001509         0   0.00%
    mobd_e    EX_mobd_e 0.001509         0   0.00%
     nh4_e     EX_nh4_e    5.266         0   0.00%
      o2_e      EX_o2_e    11.65         0   0.00%
      pi_e      EX_pi_e   0.4238         0   0.00%
     so4_e     EX_so4_e  0.05829         0   0.00%
     zn2_e     EX_zn2_e 0.001509         0   0.00%

Secretion
---------
Metabolite    Reaction       Flux  C-Number C-Flux
  hmfurn_c DM_hmfurn_c -0.0002131         5  0.01%
     co2_e    EX_co2_e     -11.52         1 99.99%
     h2o_e    EX_h2o_e     -24.69         0  0.00%
       h_e      EX_h_e     -4.051         0  0.00%

In [8]:
mixed1090_imat_restrictions_FBA.fluxes[:10]

3HAD180    0.002079
3HAD181    0.003118
3HAD40     0.105576
3HAD60     0.105576
3HAD80     0.105576
3KGK       0.000000
3NTD2pp    0.000000
3NTD4pp    0.000000
3NTD7pp    0.000000
3NTD9pp    0.000000
Name: fluxes, dtype: float64

Run FVA on the first 10 reactions in a model.

In [9]:
flux_variability_analysis(mixed1090_imat_restrictions, mixed1090_imat_restrictions.reactions[:10])

          minimum   maximum
3HAD180  0.002079  0.002079
3HAD181  0.003118  0.003118
3HAD40   0.105576  0.105576
3HAD60   0.105576  0.105576
3HAD80   0.105576  0.105576
3KGK     0.000000  0.000000
3NTD2pp  0.000000  0.000000
3NTD4pp  0.000000  0.000000
3NTD7pp  0.000000  0.000000
3NTD9pp  0.000000  0.000000

Set a parameter for 90% optimality.

In [10]:
flux_variability_analysis(mixed1090_imat_restrictions, mixed1090_imat_restrictions.reactions[:10], fraction_of_optimum=0.9)

          minimum   maximum
3HAD180  0.000000  0.118363
3HAD181  0.002806  0.098729
3HAD40   0.095018  0.224114
3HAD60   0.095018  0.224114
3HAD80   0.095018  0.224114
3KGK     0.000000  0.000000
3NTD2pp  0.000000  0.000000
3NTD4pp  0.000000  0.000000
3NTD7pp  0.000000  0.000000
3NTD9pp  0.000000  0.000000

In [11]:
flux_variability_analysis(mixed1090_imat_restrictions,loopless=False)

            minimum   maximum
3HAD180    0.002079  0.002079
3HAD181    0.003118  0.003118
3HAD40     0.105576  0.105576
3HAD60     0.105576  0.105576
3HAD80     0.105576  0.105576
...             ...       ...
12dgr2_ST  0.000045  0.000045
OAL_ST     0.000448  0.000448
OA4L_ST    0.000000  0.000000
OA5L_ST    0.000448  0.000448
OA4VL_ST   0.000000  0.000000

[2545 rows x 2 columns]

Parsimonious FBA

In [12]:
#mixed1090_imat_restrictions.objective = 'Biomass_Ecoli_core'
mixed1090_imat_restrictions_FBA 
mixed1090_imat_restrictions_pFBA = cobra.flux_analysis.pfba(mixed1090_imat_restrictions)

Geometric FBA

In [13]:
mixed1090_imat_restrictions_geomfba = cobra.flux_analysis.geometric_fba(mixed1090_imat_restrictions)
mixed1090_imat_restrictions_geomfba

/home/gmvaz/Installs/miniforge3/envs/gems/lib/python3.11/site-packages/cobra/util/solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)
Could not get flux for reaction PA180abcpp, setting it to NaN. This is usually due to numerical instability.

AttributeError: Element 0 of a double array is Nan.

Run single gene deletion on the first 20 genes in the extracted model.

In [ ]:
mixed1090_imat_restrictions_results = single_gene_deletion(mixed1090_imat_restrictions, mixed1090_imat_restrictions.genes[:19])

Run single gene deletion on the first 20 genes in the base model.

In [ ]:
stmv1_deletion_results = single_gene_deletion(stm_v1, stm_v1.genes[:19])